### PROJECT ##########################################################
TARGET = newClass
PROJINC = -I.
PROJLIB = -lXm
PROBACK = *.wrl TODO *.gif *.tif *.conf # *.j*g *.rgb
######################################################################

### Build Flags ######################################################
#TMPBIN          = YES
DEBUG           = YES
#PURIFYBIN       = YES
#EFENCE					= YES
#TEMPDB          = YES
XRUN						= YES
######################################################################

### System Compiler (GNU_CC/NATIV_CC) ################################
CC_Linux  = GNU_CC
CC_SunOS  = GNU_CC
CC_IRIX   = NATIVE_CC
CC_IRIX64 = NATIVE_CC
CC_NT     = NATIVE_CC
######################################################################

### System Flags #####################################################
PRO_FLAG_Linux 	=
PRO_FLAG_SunOS  = 
PRO_FLAG_IRIX   =
PRO_FLAG_IRIX64 = 
PRO_FLAG_NT     =
######################################################################

### Package Declarations #############################################
#PERSONAL_PAK    = YES
SYSTEM_PAK      = YES
XWINDOW_PAK     = YES
#LUG_PAK         = YES 
#XPM_PAK         = YES
MOTIF_PAK       = YES
#QT_PAK          = YES
#OPENGL_PAK      = YES
#GLUT_PAK        = YES
#GLTT_PAK        = YES
#CAMERA_PAK      = YES
#INVENTOR_PAK    = YES
#COSMO3D_PAK     = YES
#OPTIMIZER_PAK   = YES
######################################################################

### Common Makefile Declarations #####################################
include ./common.mk
######################################################################
# DO NOT DELETE
