/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *                 Copyright (C) 2000 by the OpenSG Forum                    *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class PointLight!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

//---------------------------------------------------------------------------
//  Includes
//---------------------------------------------------------------------------


#include <stdlib.h>
#include <stdio.h>

#include <OSGConfig.h>

#ifdef OSG_STREAM_IN_STD_NAMESPACE
#include <iostream>
#else
#include <iostream.h>
#endif

#define OSG_COMPILELIGHT
#define OSG_COMPILEPOINTLIGHTINST

#include "OSGPointLightBase.h"
#include "OSGPointLight.h"


OSG_USING_NAMESPACE

/***************************************************************************\
 *                               Types                                     *
\***************************************************************************/


/***************************************************************************\
 *                           Class variables                               *
\***************************************************************************/

const OSG::UInt32		PointLightBase::PositionFieldId;
const OSG::BitVector	PointLightBase::PositionFieldMask;

const OSG::UInt32		PointLightBase::ConstantAttenuationFieldId;
const OSG::BitVector	PointLightBase::ConstantAttenuationFieldMask;

const OSG::UInt32		PointLightBase::LinearAttenuationFieldId;
const OSG::BitVector	PointLightBase::LinearAttenuationFieldMask;

const OSG::UInt32		PointLightBase::QuadraticAttenuationFieldId;
const OSG::BitVector	PointLightBase::QuadraticAttenuationFieldMask;


const OSG::UInt32    	PointLightBase::NextFieldId; 
const OSG::BitVector 	PointLightBase::NextFieldMask;


char PointLightBase::cvsid[] = "@(#)$Id: OSGPointLightBase.cpp,v 1.2 2001/05/23 23:05:56 dirk Exp $";

/** \brief Group field description
 */

FieldDescription PointLightBase::_desc[] = 
{
    FieldDescription(SFPnt3f::getClassType(), 
                     "position", 
                     PositionFieldId, PositionFieldMask,
                     false,
                     (FieldAccessMethod) &PointLightBase::getSFPosition),
    FieldDescription(SFReal32::getClassType(), 
                     "constantAttenuation", 
                     ConstantAttenuationFieldId, ConstantAttenuationFieldMask,
                     false,
                     (FieldAccessMethod) &PointLightBase::getSFConstantAttenuation),
    FieldDescription(SFReal32::getClassType(), 
                     "linearAttenuation", 
                     LinearAttenuationFieldId, LinearAttenuationFieldMask,
                     false,
                     (FieldAccessMethod) &PointLightBase::getSFLinearAttenuation),
    FieldDescription(SFReal32::getClassType(), 
                     "quadraticAttenuation", 
                     QuadraticAttenuationFieldId, QuadraticAttenuationFieldMask,
                     false,
                     (FieldAccessMethod) &PointLightBase::getSFQuadraticAttenuation)
};

/** \brief PointLight type
 */

FieldContainerType PointLightBase::_type(
    "PointLight",
    "LightBase",
    NULL,
    (PrototypeCreateF) &PointLightBase::createEmpty,
    PointLight::initMethod,
    _desc,
    sizeof(_desc));


/***************************************************************************\
 *                           Class methods                                 *
\***************************************************************************/

/*-------------------------------------------------------------------------*\
 -  public                                                                 -
\*-------------------------------------------------------------------------*/

/*-------------------------------------------------------------------------*\
 -  protected                                                              -
\*-------------------------------------------------------------------------*/

/*-------------------------------------------------------------------------*\
 -  private                                                                -
\*-------------------------------------------------------------------------*/

/***************************************************************************\
 *                           Instance methods                              *
\***************************************************************************/

/*-------------------------------------------------------------------------*\
 -  public                                                                 -
\*-------------------------------------------------------------------------*/

//OSG_FIELD_CONTAINER_DEF(PointLightBase, PointLightPtr)

FieldContainerType &PointLightBase::getType(void) 
{
    return _type; 
} 

const FieldContainerType &PointLightBase::getType(void) const 
{
    return _type;
} 

FieldContainerPtr PointLightBase::shallowCopy(void) const 
{ 
    PointLightPtr returnValue; 

    newPtr(returnValue, dynamic_cast<const PointLight *>(this)); 

    return returnValue; 
}

UInt32 PointLightBase::getSize(void) const 
{ 
    return sizeof(PointLightBase); 
}

/*------------- constructors & destructors --------------------------------*/

/** \brief Constructor
 */

PointLightBase::PointLightBase(void) :
	_position	(), 
	_constantAttenuation	(), 
	_linearAttenuation	(), 
	_quadraticAttenuation	(), 
	Inherited() 
{
}

/** \brief Copy Constructor
 */

PointLightBase::PointLightBase(const PointLightBase &source) :
	_position		(source._position), 
	_constantAttenuation		(source._constantAttenuation), 
	_linearAttenuation		(source._linearAttenuation), 
	_quadraticAttenuation		(source._quadraticAttenuation), 
	Inherited        (source)
{
}

/** \brief Destructor
 */

PointLightBase::~PointLightBase(void)
{
}

/*------------------------------ access -----------------------------------*/

/*------------------------------- dump ----------------------------------*/

/*-------------------------------------------------------------------------*\
 -  protected                                                              -
\*-------------------------------------------------------------------------*/

/*-------------------------------------------------------------------------*\
 -  private                                                                -
\*-------------------------------------------------------------------------*/

