/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *             Copyright (C) 2000,2001 by the OpenSG Forum                   *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGCHUNKMATERIALFIELDS_H_
#define _OSGCHUNKMATERIALFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include <OSGConfig.h>

#include <OSGFieldContainerPtr.h>
#include <OSGNodeCoreFieldDataType.h>
#include <OSGSystemDef.h>

#include <OSGMaterialFields.h>

OSG_BEGIN_NAMESPACE

class ChunkMaterial;

//! ChunkMaterialPtr

typedef FCPtr<MaterialPtr, ChunkMaterial> ChunkMaterialPtr;

/*! \brief ChunkMaterialPtr field traits 
    \ingroup FieldLib
    \ingroup SingleFields
    \ingroup MultiFields
*/

template <>
struct FieldDataTraits<ChunkMaterialPtr> : 
    public FieldTraitsRecurseMapper<ChunkMaterialPtr>
{
    static DataType             _type;                       

    enum                        { StringConvertable = 0x00 };
    enum                        { bHasParent        = 0x01 };

    static DataType &getType (void) { return _type;        }

    static char     *getSName(void) { return "SFChunkMaterialPtr"; }
    static char     *getMName(void) { return "MFChunkMaterialPtr"; }
};

//! SFChunkMaterialPtr
//! \ingroup SingleFields

typedef SField<ChunkMaterialPtr> SFChunkMaterialPtr;

#ifndef OSG_COMPILECHUNKMATERIALINST
OSG_DLLEXPORT_DECL1(SField, ChunkMaterialPtr, OSG_SYSTEMLIB_DLLTMPLMAPPING)
#endif

//! MFChunkMaterialPtr
//! \ingroup MultiFields

typedef MField<ChunkMaterialPtr> MFChunkMaterialPtr;

#ifndef OSG_COMPILECHUNKMATERIALINST
OSG_DLLEXPORT_DECL1(MField, ChunkMaterialPtr, OSG_SYSTEMLIB_DLLTMPLMAPPING)
#endif

OSG_END_NAMESPACE

#define OSGCHUNKMATERIALFIELDS_HEADER_CVSID "@(#)$Id: OSGChunkMaterialFields.h,v 1.11 2002/05/24 09:48:37 vossg Exp $"

#endif /* _OSGCHUNKMATERIALFIELDS_H_ */
