/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *             Copyright (C) 2000,2001 by the OpenSG Forum                   *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGSIMPLETEXTUREDMATERIALFIELDS_H_
#define _OSGSIMPLETEXTUREDMATERIALFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include <OSGConfig.h>

#include <OSGFieldContainerPtr.h>
#include <OSGNodeCoreFieldDataType.h>
#include <OSGSystemDef.h>

#include <OSGSimpleMaterialFields.h>

OSG_BEGIN_NAMESPACE

class SimpleTexturedMaterial;

//! SimpleTexturedMaterialPtr

typedef FCPtr<SimpleMaterialPtr, SimpleTexturedMaterial> SimpleTexturedMaterialPtr;

/*! \brief SimpleTexturedMaterialPtr field traits 
    \ingroup FieldLib
    \ingroup SingleFields
    \ingroup MultiFields
*/

template <>
struct FieldDataTraits<SimpleTexturedMaterialPtr> : 
    public FieldTraitsRecurseMapper<SimpleTexturedMaterialPtr>
{
    static DataType             _type;                       

    enum                        { StringConvertable = 0x00 };
    enum                        { bHasParent        = 0x01 };

    static DataType &getType (void) { return _type;        }

    static char     *getSName(void) { return "SFSimpleTexturedMaterialPtr"; }
    static char     *getMName(void) { return "MFSimpleTexturedMaterialPtr"; }
};

//! SFSimpleTexturedMaterialPtr
//! \ingroup SingleFields

typedef SField<SimpleTexturedMaterialPtr> SFSimpleTexturedMaterialPtr;

#ifndef OSG_COMPILESIMPLETEXTUREDMATERIALINST
#if defined(__sgi)

#pragma do_not_instantiate SField<SimpleTexturedMaterialPtr>::_fieldType

#else

OSG_DLLEXPORT_DECL1(SField, SimpleTexturedMaterialPtr, OSG_SYSTEMLIB_DLLTMPLMAPPING)

#endif
#endif

//! MFSimpleTexturedMaterialPtr
//! \ingroup MultiFields

typedef MField<SimpleTexturedMaterialPtr> MFSimpleTexturedMaterialPtr;

#ifndef OSG_COMPILESIMPLETEXTUREDMATERIALINST
#if defined(__sgi)

#pragma do_not_instantiate MField<SimpleTexturedMaterialPtr>::_fieldType

#else

OSG_DLLEXPORT_DECL1(MField, SimpleTexturedMaterialPtr, OSG_SYSTEMLIB_DLLTMPLMAPPING)

#endif
#endif

OSG_END_NAMESPACE

#define OSGSIMPLETEXTUREDMATERIALFIELDS_HEADER_CVSID "@(#)$Id: OSGSimpleTexturedMaterialFields.h,v 1.4 2001/11/30 11:48:19 vossg Exp $"

#endif /* _OSGSIMPLETEXTUREDMATERIALFIELDS_H_ */
