/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2002 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class FileGrabForeground
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGFILEGRABFOREGROUNDBASE_H_
#define _OSGFILEGRABFOREGROUNDBASE_H_
#ifdef __sgi
#pragma once
#endif


#include "OSGConfig.h"
#include "OSGSystemDef.h"

#include "OSGBaseTypes.h"
#include "OSGRefPtr.h"
#include "OSGCoredNodePtr.h"

#include "OSGGrabForeground.h" // Parent

#include "OSGStringFields.h" // Name type
#include "OSGUInt32Fields.h" // Frame type
#include "OSGBoolFields.h" // Increment type
#include "OSGUInt32Fields.h" // PixelFormat type

#include "OSGFileGrabForegroundFields.h"

OSG_BEGIN_NAMESPACE

class FileGrabForeground;
class BinaryDataHandler;

//! \brief FileGrabForeground Base Class.

class OSG_SYSTEMLIB_DLLMAPPING FileGrabForegroundBase : public GrabForeground
{
  private:

    typedef GrabForeground    Inherited;

    /*==========================  PUBLIC  =================================*/
  public:

    typedef FileGrabForegroundPtr  Ptr;

    enum
    {
        NameFieldId        = Inherited::NextFieldId,
        FrameFieldId       = NameFieldId        + 1,
        IncrementFieldId   = FrameFieldId       + 1,
        PixelFormatFieldId = IncrementFieldId   + 1,
        NextFieldId        = PixelFormatFieldId + 1
    };

    static const OSG::BitVector NameFieldMask;
    static const OSG::BitVector FrameFieldMask;
    static const OSG::BitVector IncrementFieldMask;
    static const OSG::BitVector PixelFormatFieldMask;


    static const OSG::BitVector MTInfluenceMask;

    /*---------------------------------------------------------------------*/
    /*! \name                    Class Get                                 */
    /*! \{                                                                 */

    static        FieldContainerType &getClassType    (void); 
    static        UInt32              getClassTypeId  (void); 

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                FieldContainer Get                            */
    /*! \{                                                                 */

    virtual       FieldContainerType &getType  (void); 
    virtual const FieldContainerType &getType  (void) const; 

    virtual       UInt32              getContainerSize(void) const;

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                    Field Get                                 */
    /*! \{                                                                 */


           SFString            *editSFName           (void);
     const SFString            *getSFName           (void) const;
#ifndef OSG_2_PREP
           SFString            *getSFName           (void);
#endif

           SFUInt32            *editSFFrame          (void);
     const SFUInt32            *getSFFrame          (void) const;
#ifndef OSG_2_PREP
           SFUInt32            *getSFFrame          (void);
#endif

           SFBool              *editSFIncrement      (void);
     const SFBool              *getSFIncrement      (void) const;
#ifndef OSG_2_PREP
           SFBool              *getSFIncrement      (void);
#endif

           SFUInt32            *editSFPixelFormat    (void);
     const SFUInt32            *getSFPixelFormat    (void) const;
#ifndef OSG_2_PREP
           SFUInt32            *getSFPixelFormat    (void);
#endif


           std::string         &editName           (void);
     const std::string         &getName           (void) const;
#ifndef OSG_2_PREP
           std::string         &getName           (void);
#endif

           UInt32              &editFrame          (void);
     const UInt32              &getFrame          (void) const;
#ifndef OSG_2_PREP
           UInt32              &getFrame          (void);
#endif

           bool                &editIncrement      (void);
     const bool                &getIncrement      (void) const;
#ifndef OSG_2_PREP
           bool                &getIncrement      (void);
#endif

           UInt32              &editPixelFormat    (void);
     const UInt32              &getPixelFormat    (void) const;
#ifndef OSG_2_PREP
           UInt32              &getPixelFormat    (void);
#endif

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                    Field Set                                 */
    /*! \{                                                                 */

     void setName           ( const std::string &value );
     void setFrame          ( const UInt32 &value );
     void setIncrement      ( const bool &value );
     void setPixelFormat    ( const UInt32 &value );

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                       Sync                                   */
    /*! \{                                                                 */

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                   Binary Access                              */
    /*! \{                                                                 */

    virtual UInt32 getBinSize (const BitVector         &whichField);
    virtual void   copyToBin  (      BinaryDataHandler &pMem,
                               const BitVector         &whichField);
    virtual void   copyFromBin(      BinaryDataHandler &pMem,
                               const BitVector         &whichField);


    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                   Construction                               */
    /*! \{                                                                 */

    static  FileGrabForegroundPtr      create          (void); 
    static  FileGrabForegroundPtr      createEmpty     (void); 

    /*! \}                                                                 */

    /*---------------------------------------------------------------------*/
    /*! \name                       Copy                                   */
    /*! \{                                                                 */

    virtual FieldContainerPtr     shallowCopy     (void) const; 

    /*! \}                                                                 */
    /*=========================  PROTECTED  ===============================*/
  protected:

    /*---------------------------------------------------------------------*/
    /*! \name                      Fields                                  */
    /*! \{                                                                 */

    SFString            _sfName;
    SFUInt32            _sfFrame;
    SFBool              _sfIncrement;
    SFUInt32            _sfPixelFormat;

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                   Constructors                               */
    /*! \{                                                                 */

    FileGrabForegroundBase(void);
    FileGrabForegroundBase(const FileGrabForegroundBase &source);

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                   Destructors                                */
    /*! \{                                                                 */

    virtual ~FileGrabForegroundBase(void); 

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                       Sync                                   */
    /*! \{                                                                 */

#if !defined(OSG_FIXED_MFIELDSYNC)
    void executeSyncImpl(      FileGrabForegroundBase *pOther,
                         const BitVector         &whichField);

    virtual void   executeSync(      FieldContainer    &other,
                               const BitVector         &whichField);
#else
    void executeSyncImpl(      FileGrabForegroundBase *pOther,
                         const BitVector         &whichField,
                         const SyncInfo          &sInfo     );

    virtual void   executeSync(      FieldContainer    &other,
                               const BitVector         &whichField,
                               const SyncInfo          &sInfo);

    virtual void execBeginEdit     (const BitVector &whichField,
                                          UInt32     uiAspect,
                                          UInt32     uiContainerSize);

            void execBeginEditImpl (const BitVector &whichField,
                                          UInt32     uiAspect,
                                          UInt32     uiContainerSize);

    virtual void onDestroyAspect(UInt32 uiId, UInt32 uiAspect);
#endif

    /*! \}                                                                 */
    /*==========================  PRIVATE  ================================*/
  private:

    friend class FieldContainer;

    static FieldDescription   *_desc[];
    static FieldContainerType  _type;


    // prohibit default functions (move to 'public' if you need one)
    void operator =(const FileGrabForegroundBase &source);
};

//---------------------------------------------------------------------------
//   Exported Types
//---------------------------------------------------------------------------


typedef FileGrabForegroundBase *FileGrabForegroundBaseP;

typedef osgIF<FileGrabForegroundBase::isNodeCore,
              CoredNodePtr<FileGrabForeground>,
              FieldContainer::attempt_to_create_CoredNodePtr_on_non_NodeCore_FC
              >::_IRet FileGrabForegroundNodePtr;

typedef RefPtr<FileGrabForegroundPtr> FileGrabForegroundRefPtr;

OSG_END_NAMESPACE

#define OSGFILEGRABFOREGROUNDBASE_HEADER_CVSID "@(#)$Id: FCBaseTemplate_h.h,v 1.42 2008/06/09 12:26:59 vossg Exp $"

#endif /* _OSGFILEGRABFOREGROUNDBASE_H_ */
