Import('*')

sources = Split("""
    OSGGLUTWindow.cpp
    OSGGLUTWindowBase.cpp
""")

headers = Split("""
    OSGGLUTWindow.h
    OSGGLUTWindow.inl
    OSGGLUTWindowBase.h
    OSGGLUTWindowBase.inl
    OSGGLUTWindowFields.h
    OSGWindowGLUTDef.h
""")

InstallHeaders(env, headers)

def custom(env):
    env.Append(LIBS=env.get('OSG_WINDOW_GLUT_LIBS', []))

BuildLibrary(tc, 'OSGWindowGLUT', sources, updates=[custom],
             CPPPATH=ExpandCPPPath([Dir('.')] + BaseDirs + SystemDirs),
             CPPDEFINES=['OSG_BUILD_DLL', 'OSG_COMPILEWINDOWGLUTLIB',
                         'OSG_WITH_GLUT'],
             LIBPATH=['../../Base', '../../System'],
             LIBS=['OSGSystem${OSG_LIBSUF}', 'OSGBase${OSG_LIBSUF}'])
