/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *             Copyright (C) 2000-2002 by the OpenSG Forum                   *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class PrintNameActor
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


OSG_BEGIN_NAMESPACE

//----------------------------------------------------------------------------
//    State Access
//----------------------------------------------------------------------------

/*! Return the StatePtr, cast to this actor's state class
 *  PrintNameActorBaseState
 */

inline const PrintNameActorBase::PrintNameActorBaseState *
PrintNameActorBase::getCastState(void) const
{
    return reinterpret_cast<const PrintNameActorBaseState *>(getState());
}

/*! Return the StatePtr, cast to this actor's state class
 *  PrintNameActorBaseState
 */

inline PrintNameActorBase::PrintNameActorBaseState *
PrintNameActorBase::getCastState(void)
{
    return reinterpret_cast<PrintNameActorBaseState *>(getState());
}

//----------------------------------------------------------------------------
//    State Class
//----------------------------------------------------------------------------

/*! Default constructor.
 */

inline
PrintNameActorBase::PrintNameActorBaseState::PrintNameActorBaseState(void) :
      _stateTreeLevel(0),
      _stateParentNode(NullFC),
      ParentStateType()
{
}

/*! Copy constructor.
 */

inline
PrintNameActorBase::PrintNameActorBaseState::PrintNameActorBaseState(
    const PrintNameActorBaseState &source) :
      _stateTreeLevel(source._stateTreeLevel),
      _stateParentNode(source._stateParentNode),
      ParentStateType(source)
{
}

/*! Return the state element TreeLevel. For internal use only.
 */

inline const UInt32 &
PrintNameActorBase::PrintNameActorBaseState::getTreeLevel(void) const
{
    return _stateTreeLevel;
}

/*! Return the state element TreeLevel. For internal use only.
 */

inline UInt32 &
PrintNameActorBase::PrintNameActorBaseState::getTreeLevel(void)
{
    return _stateTreeLevel;
}
/*! Return the state element ParentNode. For internal use only.
 */

inline const NodePtr &
PrintNameActorBase::PrintNameActorBaseState::getParentNode(void) const
{
    return _stateParentNode;
}

/*! Return the state element ParentNode. For internal use only.
 */

inline NodePtr &
PrintNameActorBase::PrintNameActorBaseState::getParentNode(void)
{
    return _stateParentNode;
}

//----------------------------------------------------------------------------
//    Public State Access
//----------------------------------------------------------------------------

/*! Return the state element TreeLevel.
 *  \warning This state element can only be accessed after the actor was
 *  attached to an action.
 */

inline const UInt32 &
PrintNameActorBase::getTreeLevel(void) const
{
    return getCastState()->getTreeLevel();
}

/*! Return the state element TreeLevel.
 *  \warning This state element can only be accessed after the actor was
 *  attached to an action.
 */

inline UInt32 &
PrintNameActorBase::getTreeLevel(void)
{
    return getCastState()->getTreeLevel();
}

inline void
PrintNameActorBase::setTreeLevel(const UInt32 &stateVal)
{
    getCastState()->getTreeLevel() = stateVal;
}

/*! Return the state element ParentNode.
 *  \warning This state element can only be accessed after the actor was
 *  attached to an action.
 */

inline const NodePtr &
PrintNameActorBase::getParentNode(void) const
{
    return getCastState()->getParentNode();
}

/*! Return the state element ParentNode.
 *  \warning This state element can only be accessed after the actor was
 *  attached to an action.
 */

inline NodePtr &
PrintNameActorBase::getParentNode(void)
{
    return getCastState()->getParentNode();
}

inline void
PrintNameActorBase::setParentNode(const NodePtr &stateVal)
{
    getCastState()->getParentNode() = stateVal;
}

/*! Return the state element NumNodes.
 */

inline const UInt32 &
PrintNameActorBase::getNumNodes(void) const
{
    return _stateNumNodes;
}

/*! Return the state element NumNodes.
 */

inline UInt32 &
PrintNameActorBase::getNumNodes(void)
{
    return _stateNumNodes;
}

/*! Set the state element NumNodes.
 */

inline void
PrintNameActorBase::setNumNodes(const UInt32 &stateVal)
{
    _stateNumNodes = stateVal;
}

//----------------------------------------------------------------------------
//    Protected State Access
//----------------------------------------------------------------------------


OSG_END_NAMESPACE

#define OSGPRINTNAMEACTORBASE_INLINE_CVSID "@(#)$Id: OSGPrintNameActorBase.inl,v 1.3 2004/09/10 15:00:48 neumannc Exp $"
