/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *                 Copyright (C) 2000 by the OpenSG Forum                    *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGTRANSFORMFIELDS_H_
#define _OSGTRANSFORMFIELDS_H_
#ifdef __sgi
#pragma once
#endif

//---------------------------------------------------------------------------
//  Includes
//---------------------------------------------------------------------------

#include <OSGConfig.h>

#include <OSGFieldContainerPtr.h>
#include <OSGMiscDef.h>

OSG_BEGIN_NAMESPACE

//---------------------------------------------------------------------------
//  Forward References
//---------------------------------------------------------------------------

class Transform;
/** \brief TransformPtr
 */
typedef FCPtr<NodeCorePtr, Transform> TransformPtr;

/** \ingroup FieldLib Transform
 *  \brief TransformPtr field traits 
 */

template <>
struct FieldDataTraits<TransformPtr> : public Traits
{
    enum                        { StringConvertable = 0x00      };

    static char *getSName(void) { return "SFTransformPtr"; }
    static char *getMName(void) { return "MFTransformPtr"; }
};

/** \brief SFTransformPtr
 */
typedef SField<TransformPtr> SFTransformPtr;

#ifndef OSG_COMPILETRANSFORMINST
#if defined(__sgi)

#pragma do_not_instantiate SField<TransformPtr>::_fieldType

#else

OSG_DLLEXPORT_DECL1(SField, TransformPtr, OSG_MISC_DLLTMPLMAPPING)

#endif
#endif

/** \brief MFTransformPtr
 */
typedef MField<TransformPtr> MFTransformPtr;

#ifndef OSG_COMPILETRANSFORMINST
#if defined(__sgi)

#pragma do_not_instantiate MField<TransformPtr>::_fieldType

#else

OSG_DLLEXPORT_DECL1(MField, TransformPtr, OSG_MISC_DLLTMPLMAPPING)

#endif
#endif

OSG_END_NAMESPACE

#endif /* _OSGTRANSFORMFIELDS_H_ */
