/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *             Copyright (C) 2000,2001 by the OpenSG Forum                   *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class Transform!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

//---------------------------------------------------------------------------
//  Includes
//---------------------------------------------------------------------------


#define OSG_COMPILESYSTEMLIB
#define OSG_COMPILETRANSFORMINST

#include <stdlib.h>
#include <stdio.h>

#include <OSGConfig.h>

#include "OSGTransformBase.h"
#include "OSGTransform.h"


OSG_USING_NAMESPACE

/***************************************************************************\
 *                               Types                                     *
\***************************************************************************/

OSG_BEGIN_NAMESPACE

#if defined(__sgi)

#pragma instantiate SField<TransformPtr>::_fieldType
#pragma instantiate MField<TransformPtr>::_fieldType

#else

OSG_DLLEXPORT_DEF1(SField, TransformPtr, OSG_SYSTEMLIB_DLLTMPLMAPPING)
OSG_DLLEXPORT_DEF1(MField, TransformPtr, OSG_SYSTEMLIB_DLLTMPLMAPPING)

#endif

OSG_END_NAMESPACE

/***************************************************************************\
 *                           Class variables                               *
\***************************************************************************/

const OSG::BitVector	TransformBase::MatrixFieldMask = 
    (1 << TransformBase::MatrixFieldId);



char TransformBase::cvsid[] = "@(#)$Id: OSGTransformBase.cpp,v 1.7 2001/07/09 14:44:54 vossg Exp $";

/** \brief Group field description
 */

FieldDescription TransformBase::_desc[] = 
{
    FieldDescription(SFMatrix::getClassType(), 
                     "matrix", 
                     MatrixFieldId, MatrixFieldMask,
                     false,
                     (FieldAccessMethod) &TransformBase::getSFMatrix)
};

/** \brief Transform type
 */

FieldContainerType TransformBase::_type(
    "Transform",
    "NodeCore",
    NULL,
    (PrototypeCreateF) &TransformBase::createEmpty,
    Transform::initMethod,
    _desc,
    sizeof(_desc));


/***************************************************************************\
 *                           Class methods                                 *
\***************************************************************************/

/*-------------------------------------------------------------------------*\
 -  public                                                                 -
\*-------------------------------------------------------------------------*/

/*-------------------------------------------------------------------------*\
 -  protected                                                              -
\*-------------------------------------------------------------------------*/

/*-------------------------------------------------------------------------*\
 -  private                                                                -
\*-------------------------------------------------------------------------*/

/***************************************************************************\
 *                           Instance methods                              *
\***************************************************************************/

/*-------------------------------------------------------------------------*\
 -  public                                                                 -
\*-------------------------------------------------------------------------*/

//OSG_FIELD_CONTAINER_DEF(TransformBase, TransformPtr)

FieldContainerType &TransformBase::getType(void) 
{
    return _type; 
} 

const FieldContainerType &TransformBase::getType(void) const 
{
    return _type;
} 

FieldContainerPtr TransformBase::shallowCopy(void) const 
{ 
    TransformPtr returnValue; 

    newPtr(returnValue, dynamic_cast<const Transform *>(this)); 

    return returnValue; 
}

UInt32 TransformBase::getSize(void) const 
{ 
    return sizeof(TransformBase); 
}


void TransformBase::executeSync(      FieldContainer &other,
                                    const BitVector      &whichField)
{
    this->executeSyncImpl((TransformBase *) &other, whichField);
}

/*------------- constructors & destructors --------------------------------*/

/** \brief Constructor
 */

TransformBase::TransformBase(void) :
	_sfMatrix	(), 
	Inherited() 
{
}

/** \brief Copy Constructor
 */

TransformBase::TransformBase(const TransformBase &source) :
	_sfMatrix		(source._sfMatrix), 
	Inherited        (source)
{
}

/** \brief Destructor
 */

TransformBase::~TransformBase(void)
{
}

/*------------------------------ access -----------------------------------*/

UInt32 TransformBase::getBinSize(const BitVector &whichField)
{
    UInt32 returnValue = Inherited::getBinSize(whichField);

    if(FieldBits::NoField != (MatrixFieldMask & whichField))
    {
        returnValue += _sfMatrix.getBinSize();
    }


    return returnValue;
}

MemoryHandle TransformBase::copyToBin(      MemoryHandle  pMem,
                                          const BitVector    &whichField)
{
    pMem = Inherited::copyToBin(pMem, whichField);

    if(FieldBits::NoField != (MatrixFieldMask & whichField))
    {
        pMem = _sfMatrix.copyToBin(pMem);
    }


    return pMem;
}

MemoryHandle TransformBase::copyFromBin(      MemoryHandle  pMem,
                                            const BitVector    &whichField)
{
    pMem = Inherited::copyFromBin(pMem, whichField);

    if(FieldBits::NoField != (MatrixFieldMask & whichField))
    {
        pMem = _sfMatrix.copyFromBin(pMem);
    }


    return pMem;
}

/*------------------------------- dump ----------------------------------*/

/*-------------------------------------------------------------------------*\
 -  protected                                                              -
\*-------------------------------------------------------------------------*/


void TransformBase::executeSyncImpl(      TransformBase *pOther,
                                        const BitVector         &whichField)
{

    Inherited::executeSyncImpl(pOther, whichField);

    if(FieldBits::NoField != (MatrixFieldMask & whichField))
    {
        _sfMatrix.syncWith(pOther->_sfMatrix);
    }


}

/*-------------------------------------------------------------------------*\
 -  private                                                                -
\*-------------------------------------------------------------------------*/

