# Base

import os.path

Import('*')

headers, sources, tests, generated = ProcessDirs(BaseDirs)
InstallHeaders(env, headers)

def custom(env):
    env.Append(LIBS=env.get('OSG_BASE_LIBS', []))

BuildLibrary(tc, 'OSGBase', sources, updates=[custom],
             CPPDEFINES=['OSG_BUILD_DLL', 'OSG_COMPILEBASELIB'],
             CPPPATH=ExpandCPPPath(BaseDirs, generated))
