Import('*')

headers, sources, tests, generated = ProcessDirs(SystemDirs)
InstallHeaders(env, headers)

def custom(env):
    env.Append(LIBS=env.get('OSG_SYSTEM_LIBS', []))

BuildLibrary(tc, 'OSGSystem', sources,
             updates=[custom, OpenSGLibrary('OSGBase')],
             CPPDEFINES=['OSG_BUILD_DLL', 'OSG_COMPILESYSTEMLIB'],
             CPPPATH=ExpandCPPPath(SystemDirs + BaseDirs, generated))
