#!gmake

OSGCOMMON ?= Common

#ifndef OSGPOOL
OSGPOOL         = $(shell pwd)/../..
#endif

REQUIRED_PACKAGES := Misc FieldContainer Field Log Base Action Window Misc Geometry

include $(OSGPOOL)/$(OSGCOMMON)/common.mk
include $(OSGPOOL)/$(OSGCOMMON)/commonSub.mk
