/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2002 by the OpenSG Forum                 *
 *                                                                           *
 *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class SClipPlaneChunk!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

#include <OSGConfig.h>

OSG_BEGIN_NAMESPACE


//! access the type of the class
inline
OSG::FieldContainerType &SClipPlaneChunkBase::getClassType(void)
{
    return _type; 
} 

//! access the numerical type of the class
inline
OSG::UInt32 SClipPlaneChunkBase::getClassTypeId(void) 
{
    return _type.getId(); 
} 

//! create a new instance of the class
inline
SClipPlaneChunkPtr SClipPlaneChunkBase::create(void) 
{
    SClipPlaneChunkPtr fc; 

    if(getClassType().getPrototype() != OSG::NullFC) 
    {
        fc = SClipPlaneChunkPtr::dcast(
            getClassType().getPrototype()-> shallowCopy()); 
    }
    
    return fc; 
}

//! create an empty new instance of the class, do not copy the prototype
inline
SClipPlaneChunkPtr SClipPlaneChunkBase::createEmpty(void) 
{ 
    SClipPlaneChunkPtr returnValue; 
    
    newPtr(returnValue); 

    return returnValue; 
}


/*------------------------------ get -----------------------------------*/

//! Get the SClipPlaneChunk::_sfEquation field.
inline
SFVec4f *SClipPlaneChunkBase::getSFEquation(void)
{
    return &_sfEquation;
}


//! Get the value of the SClipPlaneChunk::_sfEquation field.
inline
Vec4f &SClipPlaneChunkBase::getEquation(void)
{
    return _sfEquation.getValue();
}

//! Get the value of the SClipPlaneChunk::_sfEquation field.
inline
const Vec4f &SClipPlaneChunkBase::getEquation(void) const
{
    return _sfEquation.getValue();
}

//! Set the value of the SClipPlaneChunk::_sfEquation field.
inline
void SClipPlaneChunkBase::setEquation(const Vec4f &value)
{
    _sfEquation.setValue(value);
}


OSG_END_NAMESPACE

#define OSGSCLIPPLANECHUNKBASE_INLINE_CVSID "@(#)$Id: OSGSClipPlaneChunkBase.inl,v 1.1 2007/04/26 15:22:01 a-m-z Exp $"

