/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *             Copyright (C) 2000,2001 by the OpenSG Forum                   *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGSTATEFIELDS_H_
#define _OSGSTATEFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include <OSGConfig.h>

#include <OSGFieldContainerPtr.h>
#include <OSGNodeCoreFieldDataType.h>
#include <OSGSystemDef.h>

#include <OSGFieldContainerFields.h>

OSG_BEGIN_NAMESPACE

class State;

#if !defined(OSG_DO_DOC)   // created as a dummy class, remove to prevent doubles
//! StatePtr

typedef FCPtr<FieldContainerPtr, State> StatePtr;

#endif

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
/*! \brief StatePtr field traits 
    \ingroup BaseFieldSingle
    \ingroup BaseFieldMulti
*/

template <>
struct FieldDataTraits<StatePtr> : 
    public FieldTraitsRecurseMapper<StatePtr, true>
{
    static DataType             _type;                       

    enum                        { StringConvertable = 0x00 };
    enum                        { bHasParent        = 0x01 };

    static DataType &getType (void) { return _type;        }

    static char     *getSName(void) { return "SFStatePtr"; }
    static char     *getMName(void) { return "MFStatePtr"; }
};
#endif             // exclude from doc

//! SFStatePtr
//! \ingroup BaseFieldSingle

typedef SField<StatePtr> SFStatePtr;

#ifndef OSG_COMPILESTATEINST
OSG_DLLEXPORT_DECL1(SField, StatePtr, OSG_SYSTEMLIB_DLLTMPLMAPPING)
#endif

//! MFStatePtr
//! \ingroup BaseFieldMulti

typedef MField<StatePtr> MFStatePtr;

#ifndef OSG_COMPILESTATEINST
OSG_DLLEXPORT_DECL1(MField, StatePtr, OSG_SYSTEMLIB_DLLTMPLMAPPING)
#endif

OSG_END_NAMESPACE

#define OSGSTATEFIELDS_HEADER_CVSID "@(#)$Id: $"

#endif /* _OSGSTATEFIELDS_H_ */
