Import('*')

sources = Split("""
    OSGQFieldContainerView_qt.cpp
    OSGQFieldEditorFactory.cpp
    OSGQFieldEditor_qt.cpp
    OSGQFieldLabelFactory.cpp
    OSGQFieldValueLabel.cpp
    OSGQFieldView_qt.cpp
    OSGQGLManagedDesignerWidget_qt.cpp
    OSGQGLManagedWidget_qt.cpp
    OSGQGLWidget_qt.cpp
    OSGQMatrixFieldValueLabel.cpp
    OSGQNodeTreeView_qt.cpp
    OSGQPointFieldValueLabel.cpp
    OSGQSceneGraphViewFunctions.cpp
    OSGQSceneGraphView_qt.cpp
    OSGQTWindow.cpp
    OSGQTWindowBase.cpp
    OSGQTypedFieldValueLabel.cpp
    OSGQVectorFieldValueLabel.cpp
    OSGQWidgetFunctions.cpp
    OSGWindowQTPlugin.cpp
""")

headers = Split("""
    OSGQFieldContainerView_qt.h
    OSGQFieldEditorFactory.h
    OSGQFieldEditor_qt.h
    OSGQFieldLabelFactory.h
    OSGQFieldValueLabel.h
    OSGQFieldView_qt.h
    OSGQGLManagedDesignerWidget_qt.h
    OSGQGLManagedWidget_qt.h
    OSGQGLWidget_qt.h
    OSGQMatrixFieldValueLabel.h
    OSGQNodeTreeView_qt.h
    OSGQPointFieldValueLabel.h
    OSGQSceneGraphViewFunctions.h
    OSGQSceneGraphView_qt.h
    OSGQTWindow.h
    OSGQTWindowBase.h
    OSGQTWindowDataFields.h
    OSGQTWindowFields.h
    OSGQTypedFieldValueLabel.h
    OSGQVectorFieldValueLabel.h
    OSGQWidgetFunctions.h
    OSGWindowQTDef.h
    OSGWindowQTPlugin.h
    OSGQFieldContainerView_qt.inl
    OSGQFieldEditor_qt.inl
    OSGQFieldLabelFactory.inl
    OSGQFieldValueLabel.inl
    OSGQFieldView_qt.inl
    OSGQGLWidget_qt.inl
    OSGQMatrixFieldValueLabel.inl
    OSGQPointFieldValueLabel.inl
    OSGQTWindow.inl
    OSGQTWindowBase.inl
    OSGQVectorFieldValueLabel.inl
    OSGQWidgetFunctions.inl
""")

InstallHeaders(env, headers)

def custom(env):
    # By default, SCons/QT generates moc_<file>.cpp
    env['QT_MOCNAMEGENERATOR'] = lambda x, src_suffix, env: x + '_moc.cpp'
    env['QT_AUTOBUILD_MOC_SOURCES'] = 0

    # Otherwise QT/moc tries to generate .cc files.
    env['CXXFILESUFFIX'] = '.cpp'
    
    env.Append(LIBS=env.get('OSG_WINDOW_QT_LIBS', []))

if tc.is_win32():
    dep_CPPPATH = ['../WIN32']
    dep_LIBS    = ['OSGWindowWIN32']
else:
    dep_CPPPATH = ['../X']
    dep_LIBS    = ['OSGWindowX']

BuildLibrary(tc, 'OSGWindowQT', sources, tools=['qt'],
             updates=[custom, OpenSGLibrary(dep_LIBS + ['OSGSystem', 'OSGBase'])],
             includeGen=1,
             CPPPATH = ExpandCPPPath([Dir('.')] + BaseDirs + SystemDirs + map(Dir, dep_CPPPATH)),
             CPPDEFINES = ['OSG_BUILD_DLL', 'OSG_COMPILEWINDOWQTLIB',
                           'OSG_WITH_QT', 'QT_CLEAN_NAMESPACE'])
