#!gmake -r -k

OSGCOMMON ?= Common

#ifndef OSGPOOL
OSGPOOL         = $(shell pwd)/..
#endif

REQUIRED_PACKAGES := Window DrawAction Action Misc FieldContainer Field Log Base 

include $(OSGPOOL)/$(OSGCOMMON)/common.mk
include $(OSGPOOL)/$(OSGCOMMON)/commonSub.mk

