/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *             Copyright (C) 2000,2001 by the OpenSG Forum                   *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class MaterialChunk!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

//---------------------------------------------------------------------------
//  Includes
//---------------------------------------------------------------------------


#define OSG_COMPILESYSTEMLIB
#define OSG_COMPILEMATERIALCHUNKINST

#include <stdlib.h>
#include <stdio.h>

#include <OSGConfig.h>

#include "OSGMaterialChunkBase.h"
#include "OSGMaterialChunk.h"


OSG_USING_NAMESPACE

/***************************************************************************\
 *                               Types                                     *
\***************************************************************************/


/***************************************************************************\
 *                           Class variables                               *
\***************************************************************************/

const OSG::BitVector	MaterialChunkBase::DiffuseFieldMask = 
    (1 << MaterialChunkBase::DiffuseFieldId);

const OSG::BitVector	MaterialChunkBase::AmbientFieldMask = 
    (1 << MaterialChunkBase::AmbientFieldId);

const OSG::BitVector	MaterialChunkBase::SpecularFieldMask = 
    (1 << MaterialChunkBase::SpecularFieldId);

const OSG::BitVector	MaterialChunkBase::EmissionFieldMask = 
    (1 << MaterialChunkBase::EmissionFieldId);

const OSG::BitVector	MaterialChunkBase::ShininessFieldMask = 
    (1 << MaterialChunkBase::ShininessFieldId);



char MaterialChunkBase::cvsid[] = "@(#)$Id: OSGMaterialChunkBase.cpp,v 1.6 2001/07/09 07:50:58 vossg Exp $";

/** \brief Group field description
 */

FieldDescription MaterialChunkBase::_desc[] = 
{
    FieldDescription(SFColor4f::getClassType(), 
                     "sfDiffuse", 
                     DiffuseFieldId, DiffuseFieldMask,
                     false,
                     (FieldAccessMethod) &MaterialChunkBase::getSFDiffuse),
    FieldDescription(SFColor4f::getClassType(), 
                     "sfAmbient", 
                     AmbientFieldId, AmbientFieldMask,
                     false,
                     (FieldAccessMethod) &MaterialChunkBase::getSFAmbient),
    FieldDescription(SFColor4f::getClassType(), 
                     "sfSpecular", 
                     SpecularFieldId, SpecularFieldMask,
                     false,
                     (FieldAccessMethod) &MaterialChunkBase::getSFSpecular),
    FieldDescription(SFColor4f::getClassType(), 
                     "sfEmission", 
                     EmissionFieldId, EmissionFieldMask,
                     false,
                     (FieldAccessMethod) &MaterialChunkBase::getSFEmission),
    FieldDescription(SFReal32::getClassType(), 
                     "sfShininess", 
                     ShininessFieldId, ShininessFieldMask,
                     false,
                     (FieldAccessMethod) &MaterialChunkBase::getSFShininess)
};

/** \brief MaterialChunk type
 */

FieldContainerType MaterialChunkBase::_type(
    "MaterialChunk",
    "StateChunk",
    NULL,
    (PrototypeCreateF) &MaterialChunkBase::createEmpty,
    MaterialChunk::initMethod,
    _desc,
    sizeof(_desc));


/***************************************************************************\
 *                           Class methods                                 *
\***************************************************************************/

/*-------------------------------------------------------------------------*\
 -  public                                                                 -
\*-------------------------------------------------------------------------*/

/*-------------------------------------------------------------------------*\
 -  protected                                                              -
\*-------------------------------------------------------------------------*/

/*-------------------------------------------------------------------------*\
 -  private                                                                -
\*-------------------------------------------------------------------------*/

/***************************************************************************\
 *                           Instance methods                              *
\***************************************************************************/

/*-------------------------------------------------------------------------*\
 -  public                                                                 -
\*-------------------------------------------------------------------------*/

//OSG_FIELD_CONTAINER_DEF(MaterialChunkBase, MaterialChunkPtr)

FieldContainerType &MaterialChunkBase::getType(void) 
{
    return _type; 
} 

const FieldContainerType &MaterialChunkBase::getType(void) const 
{
    return _type;
} 

FieldContainerPtr MaterialChunkBase::shallowCopy(void) const 
{ 
    MaterialChunkPtr returnValue; 

    newPtr(returnValue, dynamic_cast<const MaterialChunk *>(this)); 

    return returnValue; 
}

UInt32 MaterialChunkBase::getSize(void) const 
{ 
    return sizeof(MaterialChunkBase); 
}


void MaterialChunkBase::executeSync(      FieldContainer &other,
                                    const BitVector      &whichField)
{
    this->executeSyncImpl((MaterialChunkBase *) &other, whichField);
}

/*------------- constructors & destructors --------------------------------*/

/** \brief Constructor
 */

MaterialChunkBase::MaterialChunkBase(void) :
	_sfDiffuse	(Color4f(1,1,1,0)), 
	_sfAmbient	(Color4f(.2,.2,.2,0)), 
	_sfSpecular	(Color4f(.5,.5,.5,0)), 
	_sfEmission	(Color4f(0,0,0,0)), 
	_sfShininess	(Real32(10)), 
	Inherited() 
{
}

/** \brief Copy Constructor
 */

MaterialChunkBase::MaterialChunkBase(const MaterialChunkBase &source) :
	_sfDiffuse		(source._sfDiffuse), 
	_sfAmbient		(source._sfAmbient), 
	_sfSpecular		(source._sfSpecular), 
	_sfEmission		(source._sfEmission), 
	_sfShininess		(source._sfShininess), 
	Inherited        (source)
{
}

/** \brief Destructor
 */

MaterialChunkBase::~MaterialChunkBase(void)
{
}

/*------------------------------ access -----------------------------------*/

UInt32 MaterialChunkBase::getBinSize(const BitVector &whichField)
{
    UInt32 returnValue = Inherited::getBinSize(whichField);

    if(FieldBits::NoField != (DiffuseFieldMask & whichField))
    {
        returnValue += _sfDiffuse.getBinSize();
    }

    if(FieldBits::NoField != (AmbientFieldMask & whichField))
    {
        returnValue += _sfAmbient.getBinSize();
    }

    if(FieldBits::NoField != (SpecularFieldMask & whichField))
    {
        returnValue += _sfSpecular.getBinSize();
    }

    if(FieldBits::NoField != (EmissionFieldMask & whichField))
    {
        returnValue += _sfEmission.getBinSize();
    }

    if(FieldBits::NoField != (ShininessFieldMask & whichField))
    {
        returnValue += _sfShininess.getBinSize();
    }


    return returnValue;
}

MemoryHandle MaterialChunkBase::copyToBin(      MemoryHandle  pMem,
                                          const BitVector    &whichField)
{
    pMem = Inherited::copyToBin(pMem, whichField);

    if(FieldBits::NoField != (DiffuseFieldMask & whichField))
    {
        pMem = _sfDiffuse.copyToBin(pMem);
    }

    if(FieldBits::NoField != (AmbientFieldMask & whichField))
    {
        pMem = _sfAmbient.copyToBin(pMem);
    }

    if(FieldBits::NoField != (SpecularFieldMask & whichField))
    {
        pMem = _sfSpecular.copyToBin(pMem);
    }

    if(FieldBits::NoField != (EmissionFieldMask & whichField))
    {
        pMem = _sfEmission.copyToBin(pMem);
    }

    if(FieldBits::NoField != (ShininessFieldMask & whichField))
    {
        pMem = _sfShininess.copyToBin(pMem);
    }


    return pMem;
}

MemoryHandle MaterialChunkBase::copyFromBin(      MemoryHandle  pMem,
                                            const BitVector    &whichField)
{
    pMem = Inherited::copyFromBin(pMem, whichField);

    if(FieldBits::NoField != (DiffuseFieldMask & whichField))
    {
        pMem = _sfDiffuse.copyFromBin(pMem);
    }

    if(FieldBits::NoField != (AmbientFieldMask & whichField))
    {
        pMem = _sfAmbient.copyFromBin(pMem);
    }

    if(FieldBits::NoField != (SpecularFieldMask & whichField))
    {
        pMem = _sfSpecular.copyFromBin(pMem);
    }

    if(FieldBits::NoField != (EmissionFieldMask & whichField))
    {
        pMem = _sfEmission.copyFromBin(pMem);
    }

    if(FieldBits::NoField != (ShininessFieldMask & whichField))
    {
        pMem = _sfShininess.copyFromBin(pMem);
    }


    return pMem;
}

/*------------------------------- dump ----------------------------------*/

/*-------------------------------------------------------------------------*\
 -  protected                                                              -
\*-------------------------------------------------------------------------*/


void MaterialChunkBase::executeSyncImpl(      MaterialChunkBase *pOther,
                                        const BitVector         &whichField)
{

    Inherited::executeSyncImpl(pOther, whichField);

    if(FieldBits::NoField != (DiffuseFieldMask & whichField))
    {
        _sfDiffuse.syncWith(pOther->_sfDiffuse);
    }

    if(FieldBits::NoField != (AmbientFieldMask & whichField))
    {
        _sfAmbient.syncWith(pOther->_sfAmbient);
    }

    if(FieldBits::NoField != (SpecularFieldMask & whichField))
    {
        _sfSpecular.syncWith(pOther->_sfSpecular);
    }

    if(FieldBits::NoField != (EmissionFieldMask & whichField))
    {
        _sfEmission.syncWith(pOther->_sfEmission);
    }

    if(FieldBits::NoField != (ShininessFieldMask & whichField))
    {
        _sfShininess.syncWith(pOther->_sfShininess);
    }


}

/*-------------------------------------------------------------------------*\
 -  private                                                                -
\*-------------------------------------------------------------------------*/

