/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *                     Copyright 2000,2001 by OpenSG Forum                   *
 *                                                                           *
 *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class MaterialChunk!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

//---------------------------------------------------------------------------
//  Includes
//---------------------------------------------------------------------------


#include <stdlib.h>
#include <stdio.h>

#include <OSGConfig.h>

OSG_BEGIN_NAMESPACE

/***************************************************************************\
 *                               Types                                     *
\***************************************************************************/

/***************************************************************************\
 *                           Class variables                               *
\***************************************************************************/

/***************************************************************************\
 *                           Class methods                                 *
\***************************************************************************/

/*-------------------------------------------------------------------------*\
 -  public                                                                 -
\*-------------------------------------------------------------------------*/

/*-------------------------------------------------------------------------*\
 -  protected                                                              -
\*-------------------------------------------------------------------------*/


/*-------------------------------------------------------------------------*\
 -  private                                                                -
\*-------------------------------------------------------------------------*/

/***************************************************************************\
 *                           Instance methods                              *
\***************************************************************************/

/*-------------------------------------------------------------------------*\
 -  public                                                                 -
\*-------------------------------------------------------------------------*/

inline OSG::FieldContainerType &MaterialChunkBase::getClassType(void)
{
    return _type; 
} 

inline OSG::UInt32 MaterialChunkBase::getClassTypeId(void) 
{
    return _type.getId(); 
} 

inline MaterialChunkPtr MaterialChunkBase::create(void) 
{
    MaterialChunkPtr fc; 

    if(getClassType(). getPrototype() != osg::NullFC) 
    {
        fc = MaterialChunkPtr::dcast(
            getClassType().getPrototype()-> shallowCopy()); 
    }
    
    return fc; 
}

inline MaterialChunkPtr MaterialChunkBase::createEmpty(void) 
{ 
    MaterialChunkPtr returnValue; 
    
    newPtr(returnValue); 

    return returnValue; 
}


/*------------- constructors & destructors --------------------------------*/

/*--------------------------- type information-----------------------------*/

/*------------------------------ access -----------------------------------*/

OSG_SYSTEMLIB_DLLMAPPING
SFColor4f *MaterialChunkBase::getSFDiffuse(void)
{
	return &_sfDiffuse;
}

OSG_SYSTEMLIB_DLLMAPPING
SFColor4f *MaterialChunkBase::getSFAmbient(void)
{
	return &_sfAmbient;
}

OSG_SYSTEMLIB_DLLMAPPING
SFColor4f *MaterialChunkBase::getSFSpecular(void)
{
	return &_sfSpecular;
}

OSG_SYSTEMLIB_DLLMAPPING
SFColor4f *MaterialChunkBase::getSFEmission(void)
{
	return &_sfEmission;
}

OSG_SYSTEMLIB_DLLMAPPING
SFReal32 *MaterialChunkBase::getSFShininess(void)
{
	return &_sfShininess;
}


OSG_SYSTEMLIB_DLLMAPPING
Color4f &MaterialChunkBase::getDiffuse(void)
{
	return _sfDiffuse.getValue();
}

OSG_SYSTEMLIB_DLLMAPPING
const Color4f &MaterialChunkBase::getDiffuse(void) const
{
	return _sfDiffuse.getValue();
}

OSG_SYSTEMLIB_DLLMAPPING
void MaterialChunkBase::setDiffuse( Color4f value )
{
	_sfDiffuse.setValue(value);
}

OSG_SYSTEMLIB_DLLMAPPING
Color4f &MaterialChunkBase::getAmbient(void)
{
	return _sfAmbient.getValue();
}

OSG_SYSTEMLIB_DLLMAPPING
const Color4f &MaterialChunkBase::getAmbient(void) const
{
	return _sfAmbient.getValue();
}

OSG_SYSTEMLIB_DLLMAPPING
void MaterialChunkBase::setAmbient( Color4f value )
{
	_sfAmbient.setValue(value);
}

OSG_SYSTEMLIB_DLLMAPPING
Color4f &MaterialChunkBase::getSpecular(void)
{
	return _sfSpecular.getValue();
}

OSG_SYSTEMLIB_DLLMAPPING
const Color4f &MaterialChunkBase::getSpecular(void) const
{
	return _sfSpecular.getValue();
}

OSG_SYSTEMLIB_DLLMAPPING
void MaterialChunkBase::setSpecular( Color4f value )
{
	_sfSpecular.setValue(value);
}

OSG_SYSTEMLIB_DLLMAPPING
Color4f &MaterialChunkBase::getEmission(void)
{
	return _sfEmission.getValue();
}

OSG_SYSTEMLIB_DLLMAPPING
const Color4f &MaterialChunkBase::getEmission(void) const
{
	return _sfEmission.getValue();
}

OSG_SYSTEMLIB_DLLMAPPING
void MaterialChunkBase::setEmission( Color4f value )
{
	_sfEmission.setValue(value);
}

OSG_SYSTEMLIB_DLLMAPPING
Real32 &MaterialChunkBase::getShininess(void)
{
	return _sfShininess.getValue();
}

OSG_SYSTEMLIB_DLLMAPPING
const Real32 &MaterialChunkBase::getShininess(void) const
{
	return _sfShininess.getValue();
}

OSG_SYSTEMLIB_DLLMAPPING
void MaterialChunkBase::setShininess( Real32 value )
{
	_sfShininess.setValue(value);
}



/*------------------------------ access -----------------------------------*/

/*------------------------------- size ----------------------------------*/

/*------------------------------- dump ----------------------------------*/

/*-------------------------------------------------------------------------*\
 -  protected                                                              -
\*-------------------------------------------------------------------------*/


/*-------------------------------------------------------------------------*\
 -  private                                                                -
\*-------------------------------------------------------------------------*/


OSG_END_NAMESPACE

