/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *                 Copyright (C) 2000 by the OpenSG Forum                    *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class PolygonChunk!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

//---------------------------------------------------------------------------
//  Includes
//---------------------------------------------------------------------------


#include <stdlib.h>
#include <stdio.h>

#include "OSGConfig.h"

#ifdef OSG_STREAM_IN_STD_NAMESPACE
#include <iostream>
#else
#include <iostream.h>
#endif

#define OSG_COMPILESTATE
#define OSG_COMPILEPOLYGONCHUNKINST

#include "OSGPolygonChunkBase.h"
#include "OSGPolygonChunk.h"

#include <GL/gl.h>	// CullFace defaults header
#include <GL/gl.h>	// FrontFace defaults header
#include <GL/gl.h>	// ModeFace defaults header
#include <GL/gl.h>	// Mode defaults header
#include <GL/gl.h>	// Smooth defaults header
#include <GL/gl.h>	// OffsetPoint defaults header
#include <GL/gl.h>	// OffsetLine defaults header
#include <GL/gl.h>	// OffsetFill defaults header
OSG_USING_NAMESPACE


/***************************************************************************\
 *                               Types                                     *
\***************************************************************************/


/***************************************************************************\
 *                           Class variables                               *
\***************************************************************************/

const OSG::UInt32		PolygonChunkBase::CullFaceFieldId;
const OSG::BitVector	PolygonChunkBase::CullFaceFieldMask;

const OSG::UInt32		PolygonChunkBase::FrontFaceFieldId;
const OSG::BitVector	PolygonChunkBase::FrontFaceFieldMask;

const OSG::UInt32		PolygonChunkBase::ModeFaceFieldId;
const OSG::BitVector	PolygonChunkBase::ModeFaceFieldMask;

const OSG::UInt32		PolygonChunkBase::ModeFieldId;
const OSG::BitVector	PolygonChunkBase::ModeFieldMask;

const OSG::UInt32		PolygonChunkBase::SmoothFieldId;
const OSG::BitVector	PolygonChunkBase::SmoothFieldMask;

const OSG::UInt32		PolygonChunkBase::OffsetFactorFieldId;
const OSG::BitVector	PolygonChunkBase::OffsetFactorFieldMask;

const OSG::UInt32		PolygonChunkBase::OffsetBiasFieldId;
const OSG::BitVector	PolygonChunkBase::OffsetBiasFieldMask;

const OSG::UInt32		PolygonChunkBase::OffsetPointFieldId;
const OSG::BitVector	PolygonChunkBase::OffsetPointFieldMask;

const OSG::UInt32		PolygonChunkBase::OffsetLineFieldId;
const OSG::BitVector	PolygonChunkBase::OffsetLineFieldMask;

const OSG::UInt32		PolygonChunkBase::OffsetFillFieldId;
const OSG::BitVector	PolygonChunkBase::OffsetFillFieldMask;

const OSG::UInt32		PolygonChunkBase::StippleFieldId;
const OSG::BitVector	PolygonChunkBase::StippleFieldMask;


const OSG::UInt32    	PolygonChunkBase::NextFieldId; 
const OSG::BitVector 	PolygonChunkBase::NextFieldMask;


char PolygonChunkBase::cvsid[] = "@(#)$Id: OSGPolygonChunkBase.cpp,v 1.1 2001/04/15 02:12:53 dirk Exp $";

/** \brief Group field description
 */

FieldDescription PolygonChunkBase::_desc[] = 
{
    FieldDescription(SFInt32::getClassType(), 
                     "cullFace", 
                     CullFaceFieldId, CullFaceFieldMask,
                     false,
                     (FieldAccessMethod) &PolygonChunkBase::getSFCullFace),
    FieldDescription(SFInt32::getClassType(), 
                     "frontFace", 
                     FrontFaceFieldId, FrontFaceFieldMask,
                     false,
                     (FieldAccessMethod) &PolygonChunkBase::getSFFrontFace),
    FieldDescription(SFInt32::getClassType(), 
                     "modeFace", 
                     ModeFaceFieldId, ModeFaceFieldMask,
                     false,
                     (FieldAccessMethod) &PolygonChunkBase::getSFModeFace),
    FieldDescription(SFInt32::getClassType(), 
                     "mode", 
                     ModeFieldId, ModeFieldMask,
                     false,
                     (FieldAccessMethod) &PolygonChunkBase::getSFMode),
    FieldDescription(SFBool::getClassType(), 
                     "smooth", 
                     SmoothFieldId, SmoothFieldMask,
                     false,
                     (FieldAccessMethod) &PolygonChunkBase::getSFSmooth),
    FieldDescription(SFReal32::getClassType(), 
                     "offsetFactor", 
                     OffsetFactorFieldId, OffsetFactorFieldMask,
                     false,
                     (FieldAccessMethod) &PolygonChunkBase::getSFOffsetFactor),
    FieldDescription(SFReal32::getClassType(), 
                     "offsetBias", 
                     OffsetBiasFieldId, OffsetBiasFieldMask,
                     false,
                     (FieldAccessMethod) &PolygonChunkBase::getSFOffsetBias),
    FieldDescription(SFBool::getClassType(), 
                     "offsetPoint", 
                     OffsetPointFieldId, OffsetPointFieldMask,
                     false,
                     (FieldAccessMethod) &PolygonChunkBase::getSFOffsetPoint),
    FieldDescription(SFBool::getClassType(), 
                     "offsetLine", 
                     OffsetLineFieldId, OffsetLineFieldMask,
                     false,
                     (FieldAccessMethod) &PolygonChunkBase::getSFOffsetLine),
    FieldDescription(SFBool::getClassType(), 
                     "offsetFill", 
                     OffsetFillFieldId, OffsetFillFieldMask,
                     false,
                     (FieldAccessMethod) &PolygonChunkBase::getSFOffsetFill),
    FieldDescription(MFInt32::getClassType(), 
                     "stipple", 
                     StippleFieldId, StippleFieldMask,
                     false,
                     (FieldAccessMethod) &PolygonChunkBase::getMFStipple)
};

/** \brief PolygonChunk type
 */

FieldContainerType PolygonChunkBase::_type(
    "PolygonChunk",
    "StateChunk",
    NULL,
    (PrototypeCreateF) &PolygonChunkBase::createEmpty,
    PolygonChunk::initMethod,
    _desc,
    sizeof(_desc));


/***************************************************************************\
 *                           Class methods                                 *
\***************************************************************************/

/*-------------------------------------------------------------------------*\
 -  public                                                                 -
\*-------------------------------------------------------------------------*/

/*-------------------------------------------------------------------------*\
 -  protected                                                              -
\*-------------------------------------------------------------------------*/

/*-------------------------------------------------------------------------*\
 -  private                                                                -
\*-------------------------------------------------------------------------*/

/***************************************************************************\
 *                           Instance methods                              *
\***************************************************************************/

/*-------------------------------------------------------------------------*\
 -  public                                                                 -
\*-------------------------------------------------------------------------*/

//OSG_FIELD_CONTAINER_DEF(PolygonChunkBase, PolygonChunkPtr)

FieldContainerType &PolygonChunkBase::getType(void) 
{
    return _type; 
} 

const FieldContainerType &PolygonChunkBase::getType(void) const 
{
    return _type;
} 

FieldContainerPtr PolygonChunkBase::shallowCopy(void) const 
{ 
    PolygonChunkPtr returnValue; 

    newPtr(returnValue, dynamic_cast<const PolygonChunk *>(this)); 

    return returnValue; 
}

UInt32 PolygonChunkBase::getSize(void) const 
{ 
    return sizeof(PolygonChunkBase); 
}

/*------------- constructors & destructors --------------------------------*/

/** \brief Constructor
 */

PolygonChunkBase::PolygonChunkBase(void) :
	_cullFace	(Int32(GL_FALSE)), 
	_frontFace	(Int32(GL_CCW)), 
	_modeFace	(Int32(GL_FRONT)), 
	_mode	(Int32(GL_FILL)), 
	_smooth	(Bool(GL_TRUE)), 
	_offsetFactor	(Real32(0)), 
	_offsetBias	(Real32(0)), 
	_offsetPoint	(Bool(GL_FALSE)), 
	_offsetLine	(Bool(GL_FALSE)), 
	_offsetFill	(Bool(GL_FALSE)), 
	_stipple	(), 
	Inherited() 
{
}

/** \brief Copy Constructor
 */

PolygonChunkBase::PolygonChunkBase(const PolygonChunkBase &source) :
	_cullFace		(source._cullFace), 
	_frontFace		(source._frontFace), 
	_modeFace		(source._modeFace), 
	_mode		(source._mode), 
	_smooth		(source._smooth), 
	_offsetFactor		(source._offsetFactor), 
	_offsetBias		(source._offsetBias), 
	_offsetPoint		(source._offsetPoint), 
	_offsetLine		(source._offsetLine), 
	_offsetFill		(source._offsetFill), 
	_stipple		(source._stipple), 
	Inherited        (source)
{
}

/** \brief Destructor
 */

PolygonChunkBase::~PolygonChunkBase(void)
{
}

/*------------------------------ access -----------------------------------*/

/*------------------------------- dump ----------------------------------*/

/*-------------------------------------------------------------------------*\
 -  protected                                                              -
\*-------------------------------------------------------------------------*/

/*-------------------------------------------------------------------------*\
 -  private                                                                -
\*-------------------------------------------------------------------------*/

