/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *                     Copyright 2000,2001 by OpenSG Forum                   *
 *                                                                           *
 *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class PolygonChunk!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

//---------------------------------------------------------------------------
//  Includes
//---------------------------------------------------------------------------


#include <stdlib.h>
#include <stdio.h>

#include <OSGConfig.h>

OSG_BEGIN_NAMESPACE

/***************************************************************************\
 *                               Types                                     *
\***************************************************************************/

/***************************************************************************\
 *                           Class variables                               *
\***************************************************************************/

/***************************************************************************\
 *                           Class methods                                 *
\***************************************************************************/

/*-------------------------------------------------------------------------*\
 -  public                                                                 -
\*-------------------------------------------------------------------------*/

/*-------------------------------------------------------------------------*\
 -  protected                                                              -
\*-------------------------------------------------------------------------*/


/*-------------------------------------------------------------------------*\
 -  private                                                                -
\*-------------------------------------------------------------------------*/

/***************************************************************************\
 *                           Instance methods                              *
\***************************************************************************/

/*-------------------------------------------------------------------------*\
 -  public                                                                 -
\*-------------------------------------------------------------------------*/

inline OSG::FieldContainerType &PolygonChunkBase::getClassType(void)
{
    return _type; 
} 

inline OSG::UInt32 PolygonChunkBase::getClassTypeId(void) 
{
    return _type.getId(); 
} 

inline PolygonChunkPtr PolygonChunkBase::create(void) 
{
    PolygonChunkPtr fc; 

    if(getClassType(). getPrototype() != osg::NullFC) 
    {
        fc = PolygonChunkPtr::dcast(
            getClassType().getPrototype()-> shallowCopy()); 
    }
    
    return fc; 
}

inline PolygonChunkPtr PolygonChunkBase::createEmpty(void) 
{ 
    PolygonChunkPtr returnValue; 
    
    newPtr(returnValue); 

    return returnValue; 
}


/*------------- constructors & destructors --------------------------------*/

/*--------------------------- type information-----------------------------*/

/*------------------------------ access -----------------------------------*/

OSG_SYSTEMLIB_DLLMAPPING
SFInt32 *PolygonChunkBase::getSFCullFace(void)
{
	return &_sfCullFace;
}

OSG_SYSTEMLIB_DLLMAPPING
SFInt32 *PolygonChunkBase::getSFFrontFace(void)
{
	return &_sfFrontFace;
}

OSG_SYSTEMLIB_DLLMAPPING
SFInt32 *PolygonChunkBase::getSFModeFace(void)
{
	return &_sfModeFace;
}

OSG_SYSTEMLIB_DLLMAPPING
SFInt32 *PolygonChunkBase::getSFMode(void)
{
	return &_sfMode;
}

OSG_SYSTEMLIB_DLLMAPPING
SFBool *PolygonChunkBase::getSFSmooth(void)
{
	return &_sfSmooth;
}

OSG_SYSTEMLIB_DLLMAPPING
SFReal32 *PolygonChunkBase::getSFOffsetFactor(void)
{
	return &_sfOffsetFactor;
}

OSG_SYSTEMLIB_DLLMAPPING
SFReal32 *PolygonChunkBase::getSFOffsetBias(void)
{
	return &_sfOffsetBias;
}

OSG_SYSTEMLIB_DLLMAPPING
SFBool *PolygonChunkBase::getSFOffsetPoint(void)
{
	return &_sfOffsetPoint;
}

OSG_SYSTEMLIB_DLLMAPPING
SFBool *PolygonChunkBase::getSFOffsetLine(void)
{
	return &_sfOffsetLine;
}

OSG_SYSTEMLIB_DLLMAPPING
SFBool *PolygonChunkBase::getSFOffsetFill(void)
{
	return &_sfOffsetFill;
}

OSG_SYSTEMLIB_DLLMAPPING
MFInt32 *PolygonChunkBase::getMFStipple(void)
{
	return &_mfStipple;
}


OSG_SYSTEMLIB_DLLMAPPING
Int32 &PolygonChunkBase::getCullFace(void)
{
	return _sfCullFace.getValue();
}

OSG_SYSTEMLIB_DLLMAPPING
const Int32 &PolygonChunkBase::getCullFace(void) const
{
	return _sfCullFace.getValue();
}

OSG_SYSTEMLIB_DLLMAPPING
void PolygonChunkBase::setCullFace( const Int32 &value )
{
	_sfCullFace.setValue(value);
}

OSG_SYSTEMLIB_DLLMAPPING
Int32 &PolygonChunkBase::getFrontFace(void)
{
	return _sfFrontFace.getValue();
}

OSG_SYSTEMLIB_DLLMAPPING
const Int32 &PolygonChunkBase::getFrontFace(void) const
{
	return _sfFrontFace.getValue();
}

OSG_SYSTEMLIB_DLLMAPPING
void PolygonChunkBase::setFrontFace( const Int32 &value )
{
	_sfFrontFace.setValue(value);
}

OSG_SYSTEMLIB_DLLMAPPING
Int32 &PolygonChunkBase::getModeFace(void)
{
	return _sfModeFace.getValue();
}

OSG_SYSTEMLIB_DLLMAPPING
const Int32 &PolygonChunkBase::getModeFace(void) const
{
	return _sfModeFace.getValue();
}

OSG_SYSTEMLIB_DLLMAPPING
void PolygonChunkBase::setModeFace( const Int32 &value )
{
	_sfModeFace.setValue(value);
}

OSG_SYSTEMLIB_DLLMAPPING
Int32 &PolygonChunkBase::getMode(void)
{
	return _sfMode.getValue();
}

OSG_SYSTEMLIB_DLLMAPPING
const Int32 &PolygonChunkBase::getMode(void) const
{
	return _sfMode.getValue();
}

OSG_SYSTEMLIB_DLLMAPPING
void PolygonChunkBase::setMode( const Int32 &value )
{
	_sfMode.setValue(value);
}

OSG_SYSTEMLIB_DLLMAPPING
Bool &PolygonChunkBase::getSmooth(void)
{
	return _sfSmooth.getValue();
}

OSG_SYSTEMLIB_DLLMAPPING
const Bool &PolygonChunkBase::getSmooth(void) const
{
	return _sfSmooth.getValue();
}

OSG_SYSTEMLIB_DLLMAPPING
void PolygonChunkBase::setSmooth( const Bool &value )
{
	_sfSmooth.setValue(value);
}

OSG_SYSTEMLIB_DLLMAPPING
Real32 &PolygonChunkBase::getOffsetFactor(void)
{
	return _sfOffsetFactor.getValue();
}

OSG_SYSTEMLIB_DLLMAPPING
const Real32 &PolygonChunkBase::getOffsetFactor(void) const
{
	return _sfOffsetFactor.getValue();
}

OSG_SYSTEMLIB_DLLMAPPING
void PolygonChunkBase::setOffsetFactor( const Real32 &value )
{
	_sfOffsetFactor.setValue(value);
}

OSG_SYSTEMLIB_DLLMAPPING
Real32 &PolygonChunkBase::getOffsetBias(void)
{
	return _sfOffsetBias.getValue();
}

OSG_SYSTEMLIB_DLLMAPPING
const Real32 &PolygonChunkBase::getOffsetBias(void) const
{
	return _sfOffsetBias.getValue();
}

OSG_SYSTEMLIB_DLLMAPPING
void PolygonChunkBase::setOffsetBias( const Real32 &value )
{
	_sfOffsetBias.setValue(value);
}

OSG_SYSTEMLIB_DLLMAPPING
Bool &PolygonChunkBase::getOffsetPoint(void)
{
	return _sfOffsetPoint.getValue();
}

OSG_SYSTEMLIB_DLLMAPPING
const Bool &PolygonChunkBase::getOffsetPoint(void) const
{
	return _sfOffsetPoint.getValue();
}

OSG_SYSTEMLIB_DLLMAPPING
void PolygonChunkBase::setOffsetPoint( const Bool &value )
{
	_sfOffsetPoint.setValue(value);
}

OSG_SYSTEMLIB_DLLMAPPING
Bool &PolygonChunkBase::getOffsetLine(void)
{
	return _sfOffsetLine.getValue();
}

OSG_SYSTEMLIB_DLLMAPPING
const Bool &PolygonChunkBase::getOffsetLine(void) const
{
	return _sfOffsetLine.getValue();
}

OSG_SYSTEMLIB_DLLMAPPING
void PolygonChunkBase::setOffsetLine( const Bool &value )
{
	_sfOffsetLine.setValue(value);
}

OSG_SYSTEMLIB_DLLMAPPING
Bool &PolygonChunkBase::getOffsetFill(void)
{
	return _sfOffsetFill.getValue();
}

OSG_SYSTEMLIB_DLLMAPPING
const Bool &PolygonChunkBase::getOffsetFill(void) const
{
	return _sfOffsetFill.getValue();
}

OSG_SYSTEMLIB_DLLMAPPING
void PolygonChunkBase::setOffsetFill( const Bool &value )
{
	_sfOffsetFill.setValue(value);
}


OSG_SYSTEMLIB_DLLMAPPING
Int32 &PolygonChunkBase::getStipple( UInt32 index)
{
	return _mfStipple.getValue( index );
}

MFInt32 &PolygonChunkBase::getStipple(void)
{
	return _mfStipple;
}

const MFInt32 &PolygonChunkBase::getStipple(void) const
{
	return _mfStipple;
}


/*------------------------------ access -----------------------------------*/

/*------------------------------- size ----------------------------------*/

/*------------------------------- dump ----------------------------------*/

/*-------------------------------------------------------------------------*\
 -  protected                                                              -
\*-------------------------------------------------------------------------*/


/*-------------------------------------------------------------------------*\
 -  private                                                                -
\*-------------------------------------------------------------------------*/


OSG_END_NAMESPACE

