/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *             Copyright (C) 2000,2001 by the OpenSG Forum                   *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGSTATECHUNKFIELDS_H_
#define _OSGSTATECHUNKFIELDS_H_
#ifdef __sgi
#pragma once
#endif

//---------------------------------------------------------------------------
//  Includes
//---------------------------------------------------------------------------

#include <OSGConfig.h>

#include <OSGFieldContainerPtr.h>
#include <OSGSystemDef.h>

OSG_BEGIN_NAMESPACE

//---------------------------------------------------------------------------
//  Forward References
//---------------------------------------------------------------------------

class StateChunk;
/** \brief StateChunkPtr
 */
typedef FCPtr<FieldContainerPtr, StateChunk> StateChunkPtr;

/** \ingroup FieldLib StateChunk
 *  \brief StateChunkPtr field traits 
 */

template <>
struct FieldDataTraits<StateChunkPtr> : 
    public FieldTraitsRecurseMapper<StateChunkPtr>
{
    enum                        { StringConvertable = 0x00      };
    enum                        { bHasParent        = 0x01      };

    static char *getSName(void) { return "SFStateChunkPtr"; }
    static char *getMName(void) { return "MFStateChunkPtr"; }
};

/** \brief SFStateChunkPtr
 */
typedef SField<StateChunkPtr> SFStateChunkPtr;

#ifndef OSG_COMPILESTATECHUNKINST
#if defined(__sgi)

#pragma do_not_instantiate SField<StateChunkPtr>::_fieldType

#else

OSG_DLLEXPORT_DECL1(SField, StateChunkPtr, OSG_SYSTEMLIB_DLLTMPLMAPPING)

#endif
#endif

/** \brief MFStateChunkPtr
 */
typedef MField<StateChunkPtr> MFStateChunkPtr;

#ifndef OSG_COMPILESTATECHUNKINST
#if defined(__sgi)

#pragma do_not_instantiate MField<StateChunkPtr>::_fieldType

#else

OSG_DLLEXPORT_DECL1(MField, StateChunkPtr, OSG_SYSTEMLIB_DLLTMPLMAPPING)

#endif
#endif

OSG_END_NAMESPACE

#endif /* _OSGSTATECHUNKFIELDS_H_ */
