# Contrib

Import('*')
import os

ContribDirs = []

if _po.getOption('contrib_cgchunk'):
    if _po.getOption('cg'):
        ContribDirs.append(Dir('CGChunk'))
    else:
        print 'Contrib CGChunk needs cg lib, add cg=<path> to cmd line.'

if _po.getOption('contrib_cgfxmaterial'):
    if _po.getOption('cg'):
        ContribDirs.append(Dir('CGFXMaterial'))
    else:
        print 'Contrib CGFXMaterial needs cgfx lib, add cg=<path> to cmd line.'

if _po.getOption('contrib_cgfxmaterial2'):
    if _po.getOption('cg'):
        ContribDirs.append(Dir('CGFXMaterial2'))
    else:
        print 'Contrib CGFXMaterial2 needs cgfx lib, add cg=<path> to cmd line.'

if _po.getOption('contrib_ply'):
    ContribDirs.append(Dir('PLY'))

if _po.getOption('contrib_drawfunctorcore'):
    ContribDirs.append(Dir('DrawFunctorCore'))

if _po.getOption('contrib_terrain'):
    ContribDirs.append(Dir('Terrain'))

if _po.getOption('contrib_performer_loader'):
    ContribDirs.append(Dir('PerformerLoader'))

headers, sources, tests, generated = ProcessDirs(ContribDirs)
# don't forget the OSGContribDef.h file.
headers += Glob('OSG*.h')
InstallHeaders(env, headers)

def custom(env):

    if (_po.getOption('contrib_cgchunk') or _po.getOption('contrib_cgfxmaterial')) and _po.getOption('cg'):
        env.Append(CPPPATH=env.get('CGCPPPATH'))
        env.Append(LIBPATH=env.get('CGLIBPATH'))
        env.Append(LIBS=env.get('OSG_CG_LIBS'))

    if _po.getOption('contrib_performer_loader'):
        if isinstance(_po.getOption('contrib_performer_loader'), str):
                performer_cpp_path = [os.path.join(_po.getOption('contrib_performer_loader'), 'include'),
                                      os.path.join(_po.getOption('contrib_performer_loader'), 'include', 'Performer')]
                performer_lib_path = [os.path.join(_po.getOption('contrib_performer_loader'), 'lib')]
                env.Append(CPPPATH=performer_cpp_path)
                env.Append(LIBPATH=performer_lib_path)
                if env.get('PLATFORM') == 'win32':
                    env.Append(LIBS=['libpf', 'libpfdu-util'])
                else:
                    env.Append(LIBS=['pf', 'pfutil', 'pfdu'])

    env.Append(LIBS=env.get('OSG_SYSTEM_LIBS'))

if len(sources) > 0:
    BuildLibrary(tc, 'OSGContrib', sources,
                 updates=[custom, OpenSGLibrary(['OSGBase', 'OSGSystem'])],
                 CPPDEFINES=['OSG_BUILD_DLL', 'OSG_COMPILECONTRIBLIB'],
                 CPPPATH=ExpandCPPPath([Dir('.')] + SystemDirs + BaseDirs + ContribDirs, generated))
