#!gmake -r -k

OSGCOMMON ?= Common

#ifndef OSGPOOL
OSGPOOL         = $(shell pwd)/..
#endif

REQUIRED_PACKAGES := DrawAction Action Geometry Misc FieldContainer Field Base Log

include $(OSGPOOL)/$(OSGCOMMON)/common.mk
include $(OSGPOOL)/$(OSGCOMMON)/commonSub.mk

