/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *             Copyright (C) 2000,2001 by the OpenSG Forum                   *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class DynamicBackground
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGDYNAMICBACKGROUNDBASE_H_
#define _OSGDYNAMICBACKGROUNDBASE_H_
#ifdef __sgi
#pragma once
#endif

//---------------------------------------------------------------------------
//  Includes
//---------------------------------------------------------------------------

#include <OSGConfig.h>

#include <OSGBaseTypes.h>
#include <OSGFieldDescription.h>
#include <OSGFieldContainer.h>
#include <OSGSystemDef.h>
#include <OSGBackground.h>
#include <OSGColor3fFields.h>	// Color type
#include <OSGReal32Fields.h>	// Angle type
#include <OSGInt16Fields.h>	// Subdivisions type

#include <OSGDynamicBackgroundFields.h>

OSG_BEGIN_NAMESPACE

//---------------------------------------------------------------------------
//  Forward References
//---------------------------------------------------------------------------

class DynamicBackground;

//---------------------------------------------------------------------------
//   Types
//---------------------------------------------------------------------------

//---------------------------------------------------------------------------
//  Class
//---------------------------------------------------------------------------

/*! DynamicBackground Base Class. */

class OSG_SYSTEMLIB_DLLMAPPING DynamicBackgroundBase : public Background
{
  private:

    typedef Background Inherited;

  public:

    //-----------------------------------------------------------------------
    //   constants                                                           
    //-----------------------------------------------------------------------
    
    enum
    {
        ColorFieldId = Inherited::NextFieldId,
        AngleFieldId = ColorFieldId + 1,
        SubdivisionsFieldId = AngleFieldId + 1,
        NextFieldId = SubdivisionsFieldId + 1

    };

    static const osg::BitVector ColorFieldMask;
    static const osg::BitVector AngleFieldMask;
    static const osg::BitVector SubdivisionsFieldMask;

    //-----------------------------------------------------------------------
    //   enums                                                               
    //-----------------------------------------------------------------------

    //-----------------------------------------------------------------------
    //   types                                                               
    //-----------------------------------------------------------------------

    //-----------------------------------------------------------------------
    //   class functions                                                     
    //-----------------------------------------------------------------------

    static const char *getClassname(void) { return "DynamicBackgroundBase"; };

    //-----------------------------------------------------------------------
    //   instance functions                                                  
    //-----------------------------------------------------------------------

    /*-------------- general fieldcontainer declaration --------------------*/

    virtual       OSG::FieldContainerType &getType  (void); 
    virtual const OSG::FieldContainerType &getType  (void) const; 
    
    static OSG::FieldContainerType &getClassType    (void); 
    static OSG::UInt32              getClassTypeId  (void); 
    static DynamicBackgroundPtr         create          (void); 
    static DynamicBackgroundPtr         createEmpty     (void); 

    virtual OSG::FieldContainerPtr  shallowCopy     (void) const; 
    virtual OSG::UInt32             getContainerSize(void) const;

    virtual void                    executeSync(      FieldContainer &other,
                                                const BitVector      &whichField);


    virtual UInt32       getBinSize (const BitVector    &whichField);
    virtual MemoryHandle copyToBin  (      MemoryHandle  pMem,
                                     const BitVector    &whichField);
    virtual MemoryHandle copyFromBin(      MemoryHandle  pMem,
                                     const BitVector    &whichField);

    /*--------------------------- access fields ----------------------------*/

    //! Return the fields.

    inline MFColor3f	*getMFColor(void);
    inline MFReal32	*getMFAngle(void);
    inline SFInt16	*getSFSubdivisions(void);

    /*----------------------------- access ----------------------------------*/

    //!@{ Return the fields' values.

    inline       Int16	&getSubdivisions(void);
    inline const Int16	&getSubdivisions(void) const;
    inline       void	         setSubdivisions( const Int16 &value );

    inline       Color3f	               &getColor( UInt32 index );
    inline       MFColor3f &getColor(void);
    inline const MFColor3f &getColor(void) const;
    inline       Real32	               &getAngle( UInt32 index );
    inline       MFReal32 &getAngle(void);
    inline const MFReal32 &getAngle(void) const;

    //!@}

    /*-------------------------- transformation ----------------------------*/

    /*------------------------------ volume -------------------------------*/

    /*------------------------------ dump -----------------------------------*/

  protected:

    //-----------------------------------------------------------------------
    //   enums                                                               
    //-----------------------------------------------------------------------

    //-----------------------------------------------------------------------
    //   types                                                               
    //-----------------------------------------------------------------------

    //-----------------------------------------------------------------------
    //   class variables                                                     
    //-----------------------------------------------------------------------

    //-----------------------------------------------------------------------
    //   class functions                                                     
    //-----------------------------------------------------------------------

    //-----------------------------------------------------------------------
    //   instance variables                                                  
    //-----------------------------------------------------------------------

    //! The fields storing the data.

    /*! The colors of the sphere's rings.
     */
    MFColor3f	_mfColor;
    /*! The angles for the colors in radians, from 0 (top) to Pi (bottom).
     */
    MFReal32	_mfAngle;
    /*! Number of subdivisions per ring
     */
    SFInt16	_sfSubdivisions;

    //-----------------------------------------------------------------------
    //   instance functions                                                  
    //-----------------------------------------------------------------------

    DynamicBackgroundBase(void);
    DynamicBackgroundBase(const DynamicBackgroundBase &source);
    virtual ~DynamicBackgroundBase(void); 
    

    void executeSyncImpl(      DynamicBackgroundBase *pOther,
                         const BitVector         &whichField);

  private:

    //-----------------------------------------------------------------------
    //   enums                                                               
    //-----------------------------------------------------------------------

    //-----------------------------------------------------------------------
    //   types                                                               
    //-----------------------------------------------------------------------

    //-----------------------------------------------------------------------
    //   friend classes                                                      
    //-----------------------------------------------------------------------

    friend class FieldContainer;

    //-----------------------------------------------------------------------
    //   friend functions                                                    
    //-----------------------------------------------------------------------

    //-----------------------------------------------------------------------
    //   class variables                                                     
    //-----------------------------------------------------------------------

    static char cvsid[];

    static FieldDescription   *_desc[];

    static FieldContainerType  _type;


    //-----------------------------------------------------------------------
    //   class functions                                                     
    //-----------------------------------------------------------------------
    

    //-----------------------------------------------------------------------
    //   instance variables                                                  
    //-----------------------------------------------------------------------

    //-----------------------------------------------------------------------
    //   instance functions                                                  
    //-----------------------------------------------------------------------

    // prohibit default functions (move to 'public' if you need one)

    void operator =(const DynamicBackground &source);
};

//---------------------------------------------------------------------------
//   Exported Types
//---------------------------------------------------------------------------


/** \brief class pointer
 */
typedef DynamicBackgroundBase *DynamicBackgroundBaseP;

OSG_END_NAMESPACE

#endif /* _OSGDYNAMICBACKGROUNDBASE_H_ */
