/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *                     Copyright 2000,2001 by OpenSG Forum                   *
 *                                                                           *
 *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class FileGrabForeground!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

#include <OSGConfig.h>

OSG_BEGIN_NAMESPACE


//! access the type of the class
inline OSG::FieldContainerType &FileGrabForegroundBase::getClassType(void)
{
    return _type; 
} 

//! access the numerical type of the class
inline OSG::UInt32 FileGrabForegroundBase::getClassTypeId(void) 
{
    return _type.getId(); 
} 

//! create a new instance of the class
inline FileGrabForegroundPtr FileGrabForegroundBase::create(void) 
{
    FileGrabForegroundPtr fc; 

    if(getClassType().getPrototype() != osg::NullFC) 
    {
        fc = FileGrabForegroundPtr::dcast(
            getClassType().getPrototype()-> shallowCopy()); 
    }
    
    return fc; 
}

//! create an empty new instance of the class, do not copy the prototype
inline FileGrabForegroundPtr FileGrabForegroundBase::createEmpty(void) 
{ 
    FileGrabForegroundPtr returnValue; 
    
    newPtr(returnValue); 

    return returnValue; 
}


/*------------------------------ get -----------------------------------*/

OSG_SYSTEMLIB_DLLMAPPING
SFBool *FileGrabForegroundBase::getSFActive(void)
{
    return &_sfActive;
}

OSG_SYSTEMLIB_DLLMAPPING
SFString *FileGrabForegroundBase::getSFName(void)
{
    return &_sfName;
}

OSG_SYSTEMLIB_DLLMAPPING
SFUInt32 *FileGrabForegroundBase::getSFFrame(void)
{
    return &_sfFrame;
}

OSG_SYSTEMLIB_DLLMAPPING
SFBool *FileGrabForegroundBase::getSFIncrement(void)
{
    return &_sfIncrement;
}


OSG_SYSTEMLIB_DLLMAPPING
bool &FileGrabForegroundBase::getActive(void)
{
    return _sfActive.getValue();
}

OSG_SYSTEMLIB_DLLMAPPING
const bool &FileGrabForegroundBase::getActive(void) const
{
    return _sfActive.getValue();
}

OSG_SYSTEMLIB_DLLMAPPING
void FileGrabForegroundBase::setActive(const bool &value)
{
    _sfActive.setValue(value);
}

OSG_SYSTEMLIB_DLLMAPPING
string &FileGrabForegroundBase::getName(void)
{
    return _sfName.getValue();
}

OSG_SYSTEMLIB_DLLMAPPING
const string &FileGrabForegroundBase::getName(void) const
{
    return _sfName.getValue();
}

OSG_SYSTEMLIB_DLLMAPPING
void FileGrabForegroundBase::setName(const string &value)
{
    _sfName.setValue(value);
}

OSG_SYSTEMLIB_DLLMAPPING
UInt32 &FileGrabForegroundBase::getFrame(void)
{
    return _sfFrame.getValue();
}

OSG_SYSTEMLIB_DLLMAPPING
const UInt32 &FileGrabForegroundBase::getFrame(void) const
{
    return _sfFrame.getValue();
}

OSG_SYSTEMLIB_DLLMAPPING
void FileGrabForegroundBase::setFrame(const UInt32 &value)
{
    _sfFrame.setValue(value);
}

OSG_SYSTEMLIB_DLLMAPPING
bool &FileGrabForegroundBase::getIncrement(void)
{
    return _sfIncrement.getValue();
}

OSG_SYSTEMLIB_DLLMAPPING
const bool &FileGrabForegroundBase::getIncrement(void) const
{
    return _sfIncrement.getValue();
}

OSG_SYSTEMLIB_DLLMAPPING
void FileGrabForegroundBase::setIncrement(const bool &value)
{
    _sfIncrement.setValue(value);
}



OSG_END_NAMESPACE

#define OSGFILEGRABFOREGROUNDBASE_INLINE_CVSID "@(#)$Id: OSGFileGrabForegroundBase.inl,v 1.2 2002/02/04 20:14:12 dirk Exp $"

