/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *                 Copyright (C) 2000 by the OpenSG Forum                    *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class GradientBackground!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

//---------------------------------------------------------------------------
//  Includes
//---------------------------------------------------------------------------


#include <stdlib.h>
#include <stdio.h>

#include <OSGConfig.h>

#ifdef OSG_STREAM_IN_STD_NAMESPACE
#include <iostream>
#else
#include <iostream.h>
#endif

#define OSG_COMPILEWINDOW
#define OSG_COMPILEGRADIENTBACKGROUNDINST

#include "OSGGradientBackgroundBase.h"
#include "OSGGradientBackground.h"


OSG_USING_NAMESPACE

/***************************************************************************\
 *                               Types                                     *
\***************************************************************************/

OSG_BEGIN_NAMESPACE

#if defined(__sgi)

#pragma instantiate MField<GradientBackgroundPtr>::_fieldType

#else

OSG_DLLEXPORT_DEF1(MField, GradientBackgroundPtr, OSG_WINDOW_DLLTMPLMAPPING)

#endif

OSG_END_NAMESPACE

/***************************************************************************\
 *                           Class variables                               *
\***************************************************************************/

const OSG::UInt32		GradientBackgroundBase::ColorFieldId;
const OSG::BitVector	GradientBackgroundBase::ColorFieldMask;

const OSG::UInt32		GradientBackgroundBase::PositionFieldId;
const OSG::BitVector	GradientBackgroundBase::PositionFieldMask;


const OSG::UInt32    	GradientBackgroundBase::NextFieldId; 
const OSG::BitVector 	GradientBackgroundBase::NextFieldMask;


char GradientBackgroundBase::cvsid[] = "@(#)$Id: OSGGradientBackgroundBase.cpp,v 1.4 2001/05/30 16:25:24 vossg Exp $";

/** \brief Group field description
 */

FieldDescription GradientBackgroundBase::_desc[] = 
{
    FieldDescription(MFColor3f::getClassType(), 
                     "color", 
                     ColorFieldId, ColorFieldMask,
                     false,
                     (FieldAccessMethod) &GradientBackgroundBase::getMFColor),
    FieldDescription(MFReal32::getClassType(), 
                     "position", 
                     PositionFieldId, PositionFieldMask,
                     false,
                     (FieldAccessMethod) &GradientBackgroundBase::getMFPosition)
};

/** \brief GradientBackground type
 */

FieldContainerType GradientBackgroundBase::_type(
    "GradientBackground",
    "Background",
    NULL,
    (PrototypeCreateF) &GradientBackgroundBase::createEmpty,
    GradientBackground::initMethod,
    _desc,
    sizeof(_desc));


/***************************************************************************\
 *                           Class methods                                 *
\***************************************************************************/

/*-------------------------------------------------------------------------*\
 -  public                                                                 -
\*-------------------------------------------------------------------------*/

/*-------------------------------------------------------------------------*\
 -  protected                                                              -
\*-------------------------------------------------------------------------*/

/*-------------------------------------------------------------------------*\
 -  private                                                                -
\*-------------------------------------------------------------------------*/

/***************************************************************************\
 *                           Instance methods                              *
\***************************************************************************/

/*-------------------------------------------------------------------------*\
 -  public                                                                 -
\*-------------------------------------------------------------------------*/

//OSG_FIELD_CONTAINER_DEF(GradientBackgroundBase, GradientBackgroundPtr)

FieldContainerType &GradientBackgroundBase::getType(void) 
{
    return _type; 
} 

const FieldContainerType &GradientBackgroundBase::getType(void) const 
{
    return _type;
} 

FieldContainerPtr GradientBackgroundBase::shallowCopy(void) const 
{ 
    GradientBackgroundPtr returnValue; 

    newPtr(returnValue, dynamic_cast<const GradientBackground *>(this)); 

    return returnValue; 
}

UInt32 GradientBackgroundBase::getSize(void) const 
{ 
    return sizeof(GradientBackgroundBase); 
}


void GradientBackgroundBase::executeSync(FieldContainer &other,
                                    BitVector       whichField)
{
    this->executeSyncImpl((GradientBackgroundBase *) &other, whichField);
}

/*------------- constructors & destructors --------------------------------*/

/** \brief Constructor
 */

GradientBackgroundBase::GradientBackgroundBase(void) :
	_color	(), 
	_position	(), 
	Inherited() 
{
}

/** \brief Copy Constructor
 */

GradientBackgroundBase::GradientBackgroundBase(const GradientBackgroundBase &source) :
	_color		(source._color), 
	_position		(source._position), 
	Inherited        (source)
{
}

/** \brief Destructor
 */

GradientBackgroundBase::~GradientBackgroundBase(void)
{
}

/*------------------------------ access -----------------------------------*/

/*------------------------------- dump ----------------------------------*/

/*-------------------------------------------------------------------------*\
 -  protected                                                              -
\*-------------------------------------------------------------------------*/


void GradientBackgroundBase::executeSyncImpl(GradientBackgroundBase *pOther,
                                        BitVector          whichField)
{

    Inherited::executeSyncImpl(pOther, whichField);

    if(FieldBits::NoField != (ColorFieldMask & whichField))
    {
        _color.syncWith(pOther->_color);
    }

    if(FieldBits::NoField != (PositionFieldMask & whichField))
    {
        _position.syncWith(pOther->_position);
    }


}

/*-------------------------------------------------------------------------*\
 -  private                                                                -
\*-------------------------------------------------------------------------*/

