/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *                 Copyright (C) 2000 by the OpenSG Forum                    *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class PerspectiveCamera!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

//---------------------------------------------------------------------------
//  Includes
//---------------------------------------------------------------------------


#include <stdlib.h>
#include <stdio.h>

#include "OSGConfig.h"

#ifdef OSG_STREAM_IN_STD_NAMESPACE
#include <iostream>
#else
#include <iostream.h>
#endif

#define OSG_COMPILEWINDOW
#define OSG_COMPILEPERSPECTIVECAMERAINST

#include "OSGPerspectiveCameraBase.h"
#include "OSGPerspectiveCamera.h"

OSG_USING_NAMESPACE


/***************************************************************************\
 *                               Types                                     *
\***************************************************************************/

OSG_BEGIN_NAMESPACE

#if defined(__sgi)

#pragma instantiate SField<PerspectiveCameraPtr>::_fieldType
#pragma instantiate MField<PerspectiveCameraPtr>::_fieldType

#else

OSG_DLLEXPORT_DEF1(SField, PerspectiveCameraPtr, OSG_MISC_DLLTMPLMAPPING)
OSG_DLLEXPORT_DEF1(MField, PerspectiveCameraPtr, OSG_MISC_DLLTMPLMAPPING)

#endif

OSG_END_NAMESPACE

/***************************************************************************\
 *                           Class variables                               *
\***************************************************************************/

const OSG::UInt32		PerspectiveCameraBase::FovFieldId;
const OSG::BitVector	PerspectiveCameraBase::FovFieldMask;


const OSG::UInt32    	PerspectiveCameraBase::NextFieldId; 
const OSG::BitVector 	PerspectiveCameraBase::NextFieldMask;


char PerspectiveCameraBase::cvsid[] = "@(#)$Id: OSGPerspectiveCameraBase.cpp,v 1.1 2001/04/15 02:19:06 dirk Exp $";

/** \brief Group field description
 */

FieldDescription PerspectiveCameraBase::_desc[] = 
{
    FieldDescription(SFReal32::getClassType(), 
                     "fov", 
                     FovFieldId, FovFieldMask,
                     false,
                     (FieldAccessMethod) &PerspectiveCameraBase::getSFFov)
};

/** \brief PerspectiveCamera type
 */

FieldContainerType PerspectiveCameraBase::_type(
    "PerspectiveCamera",
    "Camera",
    NULL,
    (PrototypeCreateF) &PerspectiveCameraBase::createEmpty,
    PerspectiveCamera::initMethod,
    _desc,
    sizeof(_desc));


/***************************************************************************\
 *                           Class methods                                 *
\***************************************************************************/

/*-------------------------------------------------------------------------*\
 -  public                                                                 -
\*-------------------------------------------------------------------------*/

/*-------------------------------------------------------------------------*\
 -  protected                                                              -
\*-------------------------------------------------------------------------*/

/*-------------------------------------------------------------------------*\
 -  private                                                                -
\*-------------------------------------------------------------------------*/

/***************************************************************************\
 *                           Instance methods                              *
\***************************************************************************/

/*-------------------------------------------------------------------------*\
 -  public                                                                 -
\*-------------------------------------------------------------------------*/

//OSG_FIELD_CONTAINER_DEF(PerspectiveCameraBase, PerspectiveCameraPtr)

FieldContainerType &PerspectiveCameraBase::getType(void) 
{
    return _type; 
} 

const FieldContainerType &PerspectiveCameraBase::getType(void) const 
{
    return _type;
} 

FieldContainerPtr PerspectiveCameraBase::shallowCopy(void) const 
{ 
    PerspectiveCameraPtr returnValue; 

    newPtr(returnValue, dynamic_cast<const PerspectiveCamera *>(this)); 

    return returnValue; 
}

UInt32 PerspectiveCameraBase::getSize(void) const 
{ 
    return sizeof(PerspectiveCameraBase); 
}

/*------------- constructors & destructors --------------------------------*/

/** \brief Constructor
 */

PerspectiveCameraBase::PerspectiveCameraBase(void) :
	_fov	(), 
	Inherited() 
{
}

/** \brief Copy Constructor
 */

PerspectiveCameraBase::PerspectiveCameraBase(const PerspectiveCameraBase &source) :
	_fov		(source._fov), 
	Inherited        (source)
{
}

/** \brief Destructor
 */

PerspectiveCameraBase::~PerspectiveCameraBase(void)
{
}

/*------------------------------ access -----------------------------------*/

/*------------------------------- dump ----------------------------------*/

/*-------------------------------------------------------------------------*\
 -  protected                                                              -
\*-------------------------------------------------------------------------*/

/*-------------------------------------------------------------------------*\
 -  private                                                                -
\*-------------------------------------------------------------------------*/

