/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *             Copyright (C) 2000,2001 by the OpenSG Forum                   *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class TileCameraDecorator!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

//---------------------------------------------------------------------------
//  Includes
//---------------------------------------------------------------------------


#define OSG_COMPILESYSTEMLIB
#define OSG_COMPILETILECAMERADECORATORINST

#include <stdlib.h>
#include <stdio.h>

#include <OSGConfig.h>

#include "OSGTileCameraDecoratorBase.h"
#include "OSGTileCameraDecorator.h"


OSG_USING_NAMESPACE

/***************************************************************************\
 *                               Types                                     *
\***************************************************************************/

OSG_BEGIN_NAMESPACE

#if defined(__sgi)

#pragma instantiate SField<TileCameraDecoratorPtr>::_fieldType
#pragma instantiate MField<TileCameraDecoratorPtr>::_fieldType

#else

OSG_DLLEXPORT_DEF1(SField, TileCameraDecoratorPtr, OSG_SYSTEMLIB_DLLTMPLMAPPING)
OSG_DLLEXPORT_DEF1(MField, TileCameraDecoratorPtr, OSG_SYSTEMLIB_DLLTMPLMAPPING)

#endif

OSG_END_NAMESPACE

/***************************************************************************\
 *                           Class variables                               *
\***************************************************************************/

const OSG::BitVector	TileCameraDecoratorBase::LeftFieldMask = 
    (1 << TileCameraDecoratorBase::LeftFieldId);

const OSG::BitVector	TileCameraDecoratorBase::RightFieldMask = 
    (1 << TileCameraDecoratorBase::RightFieldId);

const OSG::BitVector	TileCameraDecoratorBase::BottomFieldMask = 
    (1 << TileCameraDecoratorBase::BottomFieldId);

const OSG::BitVector	TileCameraDecoratorBase::TopFieldMask = 
    (1 << TileCameraDecoratorBase::TopFieldId);



char TileCameraDecoratorBase::cvsid[] = "@(#)$Id: OSGTileCameraDecoratorBase.cpp,v 1.2 2001/07/03 14:16:32 vossg Exp $";

/** \brief Group field description
 */

FieldDescription TileCameraDecoratorBase::_desc[] = 
{
    FieldDescription(SFReal32::getClassType(), 
                     "sfLeft", 
                     LeftFieldId, LeftFieldMask,
                     false,
                     (FieldAccessMethod) &TileCameraDecoratorBase::getSFLeft),
    FieldDescription(SFReal32::getClassType(), 
                     "sfRight", 
                     RightFieldId, RightFieldMask,
                     false,
                     (FieldAccessMethod) &TileCameraDecoratorBase::getSFRight),
    FieldDescription(SFReal32::getClassType(), 
                     "sfBottom", 
                     BottomFieldId, BottomFieldMask,
                     false,
                     (FieldAccessMethod) &TileCameraDecoratorBase::getSFBottom),
    FieldDescription(SFReal32::getClassType(), 
                     "sfTop", 
                     TopFieldId, TopFieldMask,
                     true,
                     (FieldAccessMethod) &TileCameraDecoratorBase::getSFTop)
};

/** \brief TileCameraDecorator type
 */

FieldContainerType TileCameraDecoratorBase::_type(
    "TileCameraDecorator",
    "CameraDecorator",
    NULL,
    (PrototypeCreateF) &TileCameraDecoratorBase::createEmpty,
    TileCameraDecorator::initMethod,
    _desc,
    sizeof(_desc));


/***************************************************************************\
 *                           Class methods                                 *
\***************************************************************************/

/*-------------------------------------------------------------------------*\
 -  public                                                                 -
\*-------------------------------------------------------------------------*/

/*-------------------------------------------------------------------------*\
 -  protected                                                              -
\*-------------------------------------------------------------------------*/

/*-------------------------------------------------------------------------*\
 -  private                                                                -
\*-------------------------------------------------------------------------*/

/***************************************************************************\
 *                           Instance methods                              *
\***************************************************************************/

/*-------------------------------------------------------------------------*\
 -  public                                                                 -
\*-------------------------------------------------------------------------*/

//OSG_FIELD_CONTAINER_DEF(TileCameraDecoratorBase, TileCameraDecoratorPtr)

FieldContainerType &TileCameraDecoratorBase::getType(void) 
{
    return _type; 
} 

const FieldContainerType &TileCameraDecoratorBase::getType(void) const 
{
    return _type;
} 

FieldContainerPtr TileCameraDecoratorBase::shallowCopy(void) const 
{ 
    TileCameraDecoratorPtr returnValue; 

    newPtr(returnValue, dynamic_cast<const TileCameraDecorator *>(this)); 

    return returnValue; 
}

UInt32 TileCameraDecoratorBase::getSize(void) const 
{ 
    return sizeof(TileCameraDecoratorBase); 
}


void TileCameraDecoratorBase::executeSync(FieldContainer &other,
                                    BitVector       whichField)
{
    this->executeSyncImpl((TileCameraDecoratorBase *) &other, whichField);
}

/*------------- constructors & destructors --------------------------------*/

/** \brief Constructor
 */

TileCameraDecoratorBase::TileCameraDecoratorBase(void) :
	_sfLeft	(Real32(0)), 
	_sfRight	(Real32(1)), 
	_sfBottom	(Real32(0)), 
	_sfTop	(Real32(1)), 
	Inherited() 
{
}

/** \brief Copy Constructor
 */

TileCameraDecoratorBase::TileCameraDecoratorBase(const TileCameraDecoratorBase &source) :
	_sfLeft		(source._sfLeft), 
	_sfRight		(source._sfRight), 
	_sfBottom		(source._sfBottom), 
	_sfTop		(source._sfTop), 
	Inherited        (source)
{
}

/** \brief Destructor
 */

TileCameraDecoratorBase::~TileCameraDecoratorBase(void)
{
}

/*------------------------------ access -----------------------------------*/

/*------------------------------- dump ----------------------------------*/

/*-------------------------------------------------------------------------*\
 -  protected                                                              -
\*-------------------------------------------------------------------------*/


void TileCameraDecoratorBase::executeSyncImpl(TileCameraDecoratorBase *pOther,
                                        BitVector          whichField)
{

    Inherited::executeSyncImpl(pOther, whichField);

    if(FieldBits::NoField != (LeftFieldMask & whichField))
    {
        _sfLeft.syncWith(pOther->_sfLeft);
    }

    if(FieldBits::NoField != (RightFieldMask & whichField))
    {
        _sfRight.syncWith(pOther->_sfRight);
    }

    if(FieldBits::NoField != (BottomFieldMask & whichField))
    {
        _sfBottom.syncWith(pOther->_sfBottom);
    }

    if(FieldBits::NoField != (TopFieldMask & whichField))
    {
        _sfTop.syncWith(pOther->_sfTop);
    }


}

/*-------------------------------------------------------------------------*\
 -  private                                                                -
\*-------------------------------------------------------------------------*/

