/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *             Copyright (C) 2000,2001 by the OpenSG Forum                   *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGWINDOWFIELDS_H_
#define _OSGWINDOWFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include <OSGConfig.h>

#include <OSGFieldContainerPtr.h>
#include <OSGNodeCoreFieldDataType.h>
#include <OSGSystemDef.h>

#include <OSGAttachmentContainerFields.h>

OSG_BEGIN_NAMESPACE

class Window;

//! WindowPtr

typedef FCPtr<AttachmentContainerPtr, Window> WindowPtr;

/*! \brief WindowPtr field traits 
    \ingroup FieldLib
    \ingroup SingleFields
    \ingroup MultiFields
*/

template <>
struct FieldDataTraits<WindowPtr> : 
    public FieldTraitsRecurseMapper<WindowPtr>
{
    static DataType             _type;                       

    enum                        { StringConvertable = 0x00 };
    enum                        { bHasParent        = 0x01 };

    static DataType &getType (void) { return _type;        }

    static char     *getSName(void) { return "SFWindowPtr"; }
    static char     *getMName(void) { return "MFWindowPtr"; }
};

//! SFWindowPtr
//! \ingroup SingleFields

typedef SField<WindowPtr> SFWindowPtr;

#ifndef OSG_COMPILEWINDOWINST
#if defined(__sgi)

#pragma do_not_instantiate SField<WindowPtr>::_fieldType

#else

OSG_DLLEXPORT_DECL1(SField, WindowPtr, OSG_SYSTEMLIB_DLLTMPLMAPPING)

#endif
#endif

//! MFWindowPtr
//! \ingroup MultiFields

typedef MField<WindowPtr> MFWindowPtr;

#ifndef OSG_COMPILEWINDOWINST
#if defined(__sgi)

#pragma do_not_instantiate MField<WindowPtr>::_fieldType

#else

OSG_DLLEXPORT_DECL1(MField, WindowPtr, OSG_SYSTEMLIB_DLLTMPLMAPPING)

#endif
#endif

OSG_END_NAMESPACE

#define OSGWINDOWFIELDS_HEADER_CVSID "@(#)$Id: OSGWindowFields.h,v 1.13 2001/11/30 11:48:21 vossg Exp $"

#endif /* _OSGWINDOWFIELDS_H_ */
