#! /bin/sh

if ! test -w Loader/OBJ/tmp_gv; then 
    echo "Need Loader/OBJ/tmp_gv"
	echo "mkdir Loader/OBJ/tmp_gv"

    mkdir Loader/OBJ/tmp_gv
fi

if test -w Loader/OBJ/tmp_gv; then
	echo "Moving stuff out of the way"

    if test -w Loader/OBJ/OSGOBJSceneFileType.hpp; then
        echo "mv Loader/OBJ/OSGOBJSceneFileType.hpp Loader/OBJ/tmp_gv"
        mv Loader/OBJ/OSGOBJSceneFileType.hpp Loader/OBJ/tmp_gv
    fi

    if test -w Loader/OBJ/OSGOBJSceneFileType.cpp; then
        echo "mv Loader/OBJ/OSGOBJSceneFileType.cpp Loader/OBJ/tmp_gv"
        mv Loader/OBJ/OSGOBJSceneFileType.cpp Loader/OBJ/tmp_gv
    fi
fi
