#! /bin/sh

if ! test -w Base/tmp_gv; then 
    echo "Need Base/tmp_gv"
	echo "mkdir Base/tmp_gv"

    mkdir Base/tmp_gv
fi

if ! test -w Field/tmp_gv; then 
    echo "Need Field/tmp_gv"
	echo "mkdir Field/tmp_gv"

    mkdir Field/tmp_gv
fi

if test -w Base/tmp_gv; then
	echo "Moving stuff out of the way"

    if test -w Base/OSGTypeBase.h; then
        echo "mv Base/OSGTypeBase.h Base/tmp_gv"
        mv Base/OSGTypeBase.h Base/tmp_gv
    fi

    if test -w Base/OSGTypeBase.cpp; then
        echo "mv Base/OSGTypeBase.cpp Base/tmp_gv"
        mv Base/OSGTypeBase.cpp Base/tmp_gv
    fi

    if test -w Base/OSGTypeFactory.h; then
        echo "mv Base/OSGTypeFactory.h Base/tmp_gv"
        mv Base/OSGTypeFactory.h Base/tmp_gv
    fi

    if test -w Base/OSGTypeFactory.cpp; then
        echo "mv Base/OSGTypeFactory.cpp Base/tmp_gv"
        mv Base/OSGTypeFactory.cpp Base/tmp_gv
    fi

    if test -w Base/OSGConfig.h; then
        echo "mv Base/OSGConfig.h Base/tmp_gv"
        mv Base/OSGConfig.h Base/tmp_gv
    fi

    if test -w Base/OSGBaseTypeTraits.h; then
        echo "mv Base/OSGBaseTypeTraits.h Base/tmp_gv"
        mv Base/OSGBaseTypeTraits.h Base/tmp_gv
    fi


    if test -w Field/OSGFieldDataType.h; then
        echo "mv Field/OSGFieldDataType.h Field/tmp_gv"
        mv Field/OSGFieldDataType.h Field/tmp_gv
    fi

    if test -w Field/OSGField.h; then
        echo "mv Field/OSGField.h Field/tmp_gv"
        mv Field/OSGField.h Field/tmp_gv
    fi

    if test -w Field/OSGField.cpp; then
        echo "mv Field/OSMField.cpp Field/tmp_gv"
        mv Field/OSGField.cpp Field/tmp_gv
    fi

    if test -w Field/OSGMField.h; then
        echo "mv Field/OSGMField.h Field/tmp_gv"
        mv Field/OSGMField.h Field/tmp_gv
    fi

    if test -w Field/OSGMField.inl; then
        echo "mv Field/OSGMField.inl Field/tmp_gv"
        mv Field/OSGMField.inl Field/tmp_gv
    fi

    if test -w Field/OSGSField.h; then
        echo "mv Field/OSGSField.h Field/tmp_gv"
        mv Field/OSGSField.h Field/tmp_gv
    fi

    if test -w Field/OSGSField.inl; then
        echo "mv Field/OSGSField.inl Field/tmp_gv"
        mv Field/OSGSField.inl Field/tmp_gv
    fi
fi
