#! /bin/sh

if ! test -w Source/Base/Base/tmp_gv; then 
    echo "Need Source/Base/Base/tmp_gv"
	echo "mkdir Source/Base/Base/tmp_gv"

    mkdir Source/Base/Base/tmp_gv
fi

if ! test -w Source/Base/Field/tmp_gv; then 
    echo "Need Source/Base/Field/tmp_gv"
	echo "mkdir Source/Base/Field/tmp_gv"

    mkdir Source/Base/Field/tmp_gv
fi

if ! test -w Source/System/FileIO/OBJ/tmp_gv; then 
    echo "Need Source/System/FileIO/OBJ/tmp_gv"
	echo "mkdir Source/System/FileIO/OBJ/tmp_gv"

    mkdir Source/System/FileIO/OBJ/tmp_gv
fi

if ! test -w Source/System/FileIO/WRL/tmp_gv; then 
    echo "Need Source/System/FileIO/WRL/tmp_gv"
	echo "mkdir Source/System/FileIO/WRL/tmp_gv"

    mkdir Source/System/FileIO/WRL/tmp_gv
fi

if test -w Source/Base/Base/tmp_gv; then
	echo "Moving stuff out of the way"

    if test -w Source/Base/Base/OSGTypeBase.h; then
        echo "mv Source/Base/Base/OSGTypeBase.h Source/Base/Base/tmp_gv"
        mv Source/Base/Base/OSGTypeBase.h Source/Base/Base/tmp_gv
    fi

    if test -w Source/Base/Base/OSGTypeBase.cpp; then
        echo "mv Source/Base/Base/OSGTypeBase.cpp Source/Base/Base/tmp_gv"
        mv Source/Base/Base/OSGTypeBase.cpp Source/Base/Base/tmp_gv
    fi

    if test -w Source/Base/Base/OSGTypeFactory.h; then
        echo "mv Source/Base/Base/OSGTypeFactory.h Source/Base/Base/tmp_gv"
        mv Source/Base/Base/OSGTypeFactory.h Source/Base/Base/tmp_gv
    fi

    if test -w Source/Base/Base/OSGTypeFactory.cpp; then
        echo "mv Source/Base/Base/OSGTypeFactory.cpp Source/Base/Base/tmp_gv"
        mv Source/Base/Base/OSGTypeFactory.cpp Source/Base/Base/tmp_gv
    fi

#    if test -w Base/OSGConfig.h; then
#        echo "mv Base/OSGConfig.h Base/tmp_gv"
#        mv Base/OSGConfig.h Base/tmp_gv
#    fi

#    if test -w Base/OSGBaseTypeTraits.h; then
#        echo "mv Base/OSGBaseTypeTraits.h Base/tmp_gv"
#        mv Base/OSGBaseTypeTraits.h Base/tmp_gv
#    fi


#    if test -w Field/OSGFieldDataType.h; then
#        echo "mv Field/OSGFieldDataType.h Field/tmp_gv"
#        mv Field/OSGFieldDataType.h Field/tmp_gv
#    fi

#    if test -w Field/OSGField.h; then
#        echo "mv Field/OSGField.h Field/tmp_gv"
#        mv Field/OSGField.h Field/tmp_gv
#    fi

#    if test -w Field/OSGField.cpp; then
#        echo "mv Field/OSMField.cpp Field/tmp_gv"
#        mv Field/OSGField.cpp Field/tmp_gv
#    fi

#    if test -w Field/OSGMField.h; then
#        echo "mv Field/OSGMField.h Field/tmp_gv"
#        mv Field/OSGMField.h Field/tmp_gv
#    fi

#    if test -w Field/OSGMField.inl; then
#        echo "mv Field/OSGMField.inl Field/tmp_gv"
#        mv Field/OSGMField.inl Field/tmp_gv
#    fi

#    if test -w Field/OSGSField.h; then
#        echo "mv Field/OSGSField.h Field/tmp_gv"
#        mv Field/OSGSField.h Field/tmp_gv
#    fi

#    if test -w Field/OSGSField.inl; then
#        echo "mv Field/OSGSField.inl Field/tmp_gv"
#        mv Field/OSGSField.inl Field/tmp_gv
#    fi


    if test -w Source/System/FileIO/OBJ/OSGOBJSceneFileType.hpp; then
        echo "mv Source/System/FileIO/OBJ/OSGOBJSceneFileType.hpp Source/System/FileIO/OBJ/tmp_gv"
        mv Source/System/FileIO/OBJ/OSGOBJSceneFileType.hpp Source/System/FileIO/OBJ/tmp_gv
    fi

    if test -w Source/System/FileIO/OBJ/OSGOBJSceneFileType.cpp; then
        echo "mv Source/System/FileIO/OBJ/OSGOBJSceneFileType.cpp Source/System/FileIO/OBJ/tmp_gv"
        mv Source/System/FileIO/OBJ/OSGOBJSceneFileType.cpp Source/System/FileIO/OBJ/tmp_gv
    fi


    if test -w Source/System/FileIO/WRL/OSGVRMLSceneFileType.hpp; then
        echo "mv Source/System/FileIO/WRL/OSGVRMLSceneFileType.hpp Source/System/FileIO/WRL/tmp_gv"
        mv Source/System/FileIO/WRL/OSGVRMLSceneFileType.hpp Source/System/FileIO/WRL/tmp_gv
    fi

    if test -w Source/System/FileIO/WRL/OSGVRMLSceneFileType.cpp; then
        echo "mv Source/System/FileIO/WRL/OSGVRMLSceneFileType.cpp Source/System/FileIO/WRL/tmp_gv"
        mv Source/System/FileIO/WRL/OSGVRMLSceneFileType.cpp Source/System/FileIO/WRL/tmp_gv
    fi
fi
