#! /bin/sh

if test -w Base/tmp_gv; then 
	echo "Moving stuff back in"

    if test -w Base/tmp_gv/OSGTypeBase.h; then
        echo "mv Base/tmp_gv/OSGTypeBase.h Base"
        mv Base/tmp_gv/OSGTypeBase.h Base
    fi

    if test -w Base/tmp_gv/OSGTypeBase.cpp; then
        echo "mv Base/tmp_gv/OSGTypeBase.cpp Base"
        mv Base/tmp_gv/OSGTypeBase.cpp Base
    fi

    if test -w Base/tmp_gv/OSGTypeFactory.h; then
        echo "mv Base/tmp_gv/OSGTypeFactory.h Base"
        mv Base/tmp_gv/OSGTypeFactory.h Base
    fi

    if test -w Base/tmp_gv/OSGTypeFactory.cpp; then
        echo "mv Base/tmp_gv/OSGTypeFactory.cpp Base"
        mv Base/tmp_gv/OSGTypeFactory.cpp Base
    fi

#    if test -w Base/tmp_gv/OSGConfig.h; then
#        echo "mv Base/tmp_gv/OSGConfig.h Base"
#        mv Base/tmp_gv/OSGConfig.h Base
#    fi

#    if test -w Base/tmp_gv/OSGBaseTypeTraits.h; then
#        echo "mv Base/tmp_gv/OSGBaseTypeTraits.h Base"
#        mv Base/tmp_gv/OSGBaseTypeTraits.h Base
#    fi
fi

#if test -w Field/tmp_gv; then 

#    if test -w Field/tmp_gv/OSGFieldDataType.h; then
#        echo "mv Field/tmp_gv/OSGFieldDataType.h Field"
#        mv Field/tmp_gv/OSGFieldDataType.h Field
#    fi

#    if test -w Field/tmp_gv/OSGField.h; then
#        echo "mv Field/tmp_gv/OSGField.h Field"
#        mv Field/tmp_gv/OSGField.h Field
#    fi

#    if test -w Field/tmp_gv/OSGField.cpp; then
#        echo "mv Field/tmp_gv/OSMField.cpp Field"
#        mv Field/tmp_gv/OSGField.cpp Field
#    fi

#    if test -w Field/tmp_gv/OSGMField.h; then
#        echo "mv Field/tmp_gv/OSGMField.h Field"
#        mv Field/tmp_gv/OSGMField.h Field
#    fi

#    if test -w Field/tmp_gv/OSGMField.inl; then
#        echo "mv Field/tmp_gv/OSGMField.inl Field"
#        mv Field/tmp_gv/OSGMField.inl Field
#    fi

#    if test -w Field/tmp_gv/OSGSField.h; then
#        echo "mv Field/tmp_gv/OSGSField.h Field"
#        mv Field/tmp_gv/OSGSField.h Field
#    fi

#    if test -w Field/tmp_gv/OSGSField.inl; then
#        echo "mv Field/tmp_gv/OSGSField.inl Field"
#        mv Field/tmp_gv/OSGSField.inl Field
#    fi
#fi


if test -w Loader/OBJ/tmp_gv; then 

    if test -w Loader/OBJ/tmp_gv/OSGOBJSceneFileType.hpp; then
        echo "mv Loader/OBJ/tmp_gv/OSGOBJSceneFileType.hpp Loader/OBJ"
        mv Loader/OBJ/tmp_gv/OSGOBJSceneFileType.hpp Loader/OBJ
    fi

    if test -w Loader/OBJ/tmp_gv/OSGOBJSceneFileType.cpp; then
        echo "mv Loader/OBJ/tmp_gv/OSGOBJSceneFileType.cpp Loader/OBJ"
        mv Loader/OBJ/tmp_gv/OSGOBJSceneFileType.cpp Loader/OBJ
    fi

fi


if test -w Loader/WRL/tmp_gv; then 

    if test -w Loader/WRL/tmp_gv/OSGVRMLSceneFileType.hpp; then
        echo "mv Loader/WRL/tmp_gv/OSGVRMLSceneFileType.hpp Loader/WRL"
        mv Loader/WRL/tmp_gv/OSGVRMLSceneFileType.hpp Loader/WRL
    fi

    if test -w Loader/WRL/tmp_gv/OSGVRMLSceneFileType.cpp; then
        echo "mv Loader/WRL/tmp_gv/OSGVRMLSceneFileType.cpp Loader/WRL"
        mv Loader/WRL/tmp_gv/OSGVRMLSceneFileType.cpp Loader/WRL
    fi

fi
