#!/bin/sh

file=`echo $1 | sed 's/\(.*\)\/\(.*\.h\)/\2/'`

echo "Installing $1"
echo "    to $2/$file"

sed -e 's/include[ ]*<OSG/include <OpenSG\/OSG/g' -e 's/include[ ]*\"OSG/include \"OpenSG\/OSG/g' $1 > $2/$file


