/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2002 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class SHLUniformInt!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#define OSG_COMPILESHLUNIFORMINTINST

#include <stdlib.h>
#include <stdio.h>

#include <OSGConfig.h>

#include "OSGSHLUniformIntBase.h"
#include "OSGSHLUniformInt.h"


OSG_USING_NAMESPACE

const OSG::BitVector  SHLUniformIntBase::ValueFieldMask = 
    (TypeTraits<BitVector>::One << SHLUniformIntBase::ValueFieldId);

const OSG::BitVector SHLUniformIntBase::MTInfluenceMask = 
    (Inherited::MTInfluenceMask) | 
    (static_cast<BitVector>(0x0) << Inherited::NextFieldId); 


// Field descriptions

/*! \var Int32           SHLUniformIntBase::_sfValue
    parameter value
*/

//! SHLUniformInt description

FieldDescription *SHLUniformIntBase::_desc[] = 
{
    new FieldDescription(SFInt32::getClassType(), 
                     "value", 
                     ValueFieldId, ValueFieldMask,
                     false,
                     (FieldAccessMethod) &SHLUniformIntBase::getSFValue)
};


FieldContainerType SHLUniformIntBase::_type(
    "SHLUniformInt",
    "SHLUniformBase",
    NULL,
    (PrototypeCreateF) &SHLUniformIntBase::createEmpty,
    SHLUniformInt::initMethod,
    _desc,
    sizeof(_desc));

//OSG_FIELD_CONTAINER_DEF(SHLUniformIntBase, SHLUniformIntPtr)

/*------------------------------ get -----------------------------------*/

FieldContainerType &SHLUniformIntBase::getType(void) 
{
    return _type; 
} 

const FieldContainerType &SHLUniformIntBase::getType(void) const 
{
    return _type;
} 


FieldContainerPtr SHLUniformIntBase::shallowCopy(void) const 
{ 
    SHLUniformIntPtr returnValue; 

    newPtr(returnValue, dynamic_cast<const SHLUniformInt *>(this)); 

    return returnValue; 
}

UInt32 SHLUniformIntBase::getContainerSize(void) const 
{ 
    return sizeof(SHLUniformInt); 
}


void SHLUniformIntBase::executeSync(      FieldContainer &other,
                                    const BitVector      &whichField)
{
    this->executeSyncImpl((SHLUniformIntBase *) &other, whichField);
}

/*------------------------- constructors ----------------------------------*/

#ifdef OSG_WIN32_ICL
#pragma warning (disable : 383)
#endif

SHLUniformIntBase::SHLUniformIntBase(void) :
    _sfValue                  (), 
    Inherited() 
{
}

#ifdef OSG_WIN32_ICL
#pragma warning (default : 383)
#endif

SHLUniformIntBase::SHLUniformIntBase(const SHLUniformIntBase &source) :
    _sfValue                  (source._sfValue                  ), 
    Inherited                 (source)
{
}

/*-------------------------- destructors ----------------------------------*/

SHLUniformIntBase::~SHLUniformIntBase(void)
{
}

/*------------------------------ access -----------------------------------*/

UInt32 SHLUniformIntBase::getBinSize(const BitVector &whichField)
{
    UInt32 returnValue = Inherited::getBinSize(whichField);

    if(FieldBits::NoField != (ValueFieldMask & whichField))
    {
        returnValue += _sfValue.getBinSize();
    }


    return returnValue;
}

void SHLUniformIntBase::copyToBin(      BinaryDataHandler &pMem,
                                  const BitVector         &whichField)
{
    Inherited::copyToBin(pMem, whichField);

    if(FieldBits::NoField != (ValueFieldMask & whichField))
    {
        _sfValue.copyToBin(pMem);
    }


}

void SHLUniformIntBase::copyFromBin(      BinaryDataHandler &pMem,
                                    const BitVector    &whichField)
{
    Inherited::copyFromBin(pMem, whichField);

    if(FieldBits::NoField != (ValueFieldMask & whichField))
    {
        _sfValue.copyFromBin(pMem);
    }


}

void SHLUniformIntBase::executeSyncImpl(      SHLUniformIntBase *pOther,
                                        const BitVector         &whichField)
{

    Inherited::executeSyncImpl(pOther, whichField);

    if(FieldBits::NoField != (ValueFieldMask & whichField))
        _sfValue.syncWith(pOther->_sfValue);


}



#include <OSGSFieldTypeDef.inl>
#include <OSGMFieldTypeDef.inl>

OSG_BEGIN_NAMESPACE

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
DataType FieldDataTraits<SHLUniformIntPtr>::_type("SHLUniformIntPtr", "SHLUniformBasePtr");
#endif

OSG_DLLEXPORT_SFIELD_DEF1(SHLUniformIntPtr, OSG_SYSTEMLIB_DLLTMPLMAPPING);
OSG_DLLEXPORT_MFIELD_DEF1(SHLUniformIntPtr, OSG_SYSTEMLIB_DLLTMPLMAPPING);

OSG_END_NAMESPACE


/*------------------------------------------------------------------------*/
/*                              cvs id's                                  */

#ifdef OSG_SGI_CC
#pragma set woff 1174
#endif

#ifdef OSG_LINUX_ICC
#pragma warning( disable : 177 )
#endif

namespace
{
    static Char8 cvsid_cpp       [] = "@(#)$Id: OSGSHLUniformIntBase.cpp,v 1.1 2004/06/04 19:59:26 a-m-z Exp $";
    static Char8 cvsid_hpp       [] = OSGSHLUNIFORMINTBASE_HEADER_CVSID;
    static Char8 cvsid_inl       [] = OSGSHLUNIFORMINTBASE_INLINE_CVSID;

    static Char8 cvsid_fields_hpp[] = OSGSHLUNIFORMINTFIELDS_HEADER_CVSID;
}

