#!gmake -r -k

OSGCOMMON ?= Common

#ifndef OSGPOOL
OSGPOOL         = $(shell pwd)/..
#endif

REQUIRED_PACKAGES := Log Base Field FieldContainer Action Misc Geometry

include $(OSGPOOL)/$(OSGCOMMON)/common.mk
include $(OSGPOOL)/$(OSGCOMMON)/commonSub.mk
