#!gmake -k -r

OSGCOMMON ?= Common

#ifndef OSGPOOL
OSGPOOL         = $(shell pwd)/..
#endif

REQUIRED_PACKAGES := Log FieldContainer Field

include $(OSGPOOL)/$(OSGCOMMON)/common.mk
include $(OSGPOOL)/$(OSGCOMMON)/commonSub.mk

