char *FCBaseTemplate_h[]={
"/*---------------------------------------------------------------------------*\\",
" *                                OpenSG                                     *",
" *                                                                           *",
" *                                                                           *",
" *                 Copyright (C) 2000 by the OpenSG Forum                    *",
" *                                                                           *",
" *                            www.opensg.org                                 *",
" *                                                                           *",
" *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *",
" *                                                                           *",
"\\*---------------------------------------------------------------------------*/",
"/*---------------------------------------------------------------------------*\\",
" *                                License                                    *",
" *                                                                           *",
" * This library is free software; you can redistribute it and/or modify it   *",
" * under the terms of the GNU Library General Public License as published    *",
" * by the Free Software Foundation, version 2.                               *",
" *                                                                           *",
" * This library is distributed in the hope that it will be useful, but       *",
" * WITHOUT ANY WARRANTY; without even the implied warranty of                *",
" * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *",
" * Library General Public License for more details.                          *",
" *                                                                           *",
" * You should have received a copy of the GNU Library General Public         *",
" * License along with this library; if not, write to the Free Software       *",
" * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *",
" *                                                                           *",
"\\*---------------------------------------------------------------------------*/",
"/*---------------------------------------------------------------------------*\\",
" *                                Changes                                    *",
" *                                                                           *",
" *                                                                           *",
" *                                                                           *",
" *                                                                           *",
" *                                                                           *",
" *                                                                           *",
"\\*---------------------------------------------------------------------------*/",
"",
"",
"#ifndef _OSG@!CLASSNAME!@BASE_H_",
"#define _OSG@!CLASSNAME!@BASE_H_",
"#ifdef __sgi",
"#pragma once",
"#endif",
"",
"//---------------------------------------------------------------------------",
"//  Includes",
"//---------------------------------------------------------------------------",
"",
"#include <OSGConfig.h>",
"",
"#include <OSGBaseTypes.h>",
"#include <OSGFieldContainer.h>",
"#include <OSGFieldContainerPtr.h>",
"#include <OSGFieldDescription.h>",
"#include <OSG@!Parent!@.h>",
"@@BeginFieldLoop@@",
"#include <OSG@!CARDINALITY!@@!Fieldtype!@.h>	// @!Fieldname!@ type",
"@@EndFieldLoop@@",
"",
"OSG_BEGIN_NAMESPACE",
"",
"//---------------------------------------------------------------------------",
"//  Forward References",
"//---------------------------------------------------------------------------",
"",
"class @!Classname!@;",
"",
"//---------------------------------------------------------------------------",
"//   Types",
"//---------------------------------------------------------------------------",
"",
"/** \\brief @!Classname!@Ptr",
" */",
"",
"typedef FCPtr<@!Parent!@Ptr, @!Classname!@> @!Classname!@Ptr;",
"",
"//---------------------------------------------------------------------------",
"//  Class",
"//---------------------------------------------------------------------------",
"",
"/*! @!Classname!@ provides a vrml style transformation.",
" *	\\ingroup NodesLib",
" */",
"",
"class OSG_MISC_DLLMAPPING @!Classname!@Base : public @!Parent!@",
"{",
"  private:",
"",
"    typedef @!Parent!@ Inherited;",
"",
"  public:",
"",
"    //-----------------------------------------------------------------------",
"    //   constants                                                           ",
"    //-----------------------------------------------------------------------",
"    ",
"@@FieldIdsAndMasksDecl@@",
"",
"    //-----------------------------------------------------------------------",
"    //   enums                                                               ",
"    //-----------------------------------------------------------------------",
"",
"    //-----------------------------------------------------------------------",
"    //   types                                                               ",
"    //-----------------------------------------------------------------------",
"",
"    //-----------------------------------------------------------------------",
"    //   class functions                                                     ",
"    //-----------------------------------------------------------------------",
"",
"    static const char *getClassname(void) { return \"@!Classname!@Base\"; };",
"",
"    //-----------------------------------------------------------------------",
"    //   instance functions                                                  ",
"    //-----------------------------------------------------------------------",
"",
"    /*-------------- general fieldcontainer declaration --------------------*/",
"",
"    virtual       OSG::FieldContainerType &getType(void); ",
"    virtual const OSG::FieldContainerType &getType(void) const; ",
"    ",
"    static OSG::FieldContainerType &getClassType  (void); ",
"    static OSG::UInt32              getClassTypeId(void); ",
"    static @!Classname!@Ptr         create        (void); ",
"    static @!Classname!@Ptr         createEmpty   (void); ",
"",
"    virtual OSG::FieldContainerPtr shallowCopy(void) const; ",
"    virtual OSG::UInt32            getSize    (void) const;",
"",
"    /*--------------------------- access fields ----------------------------*/",
"",
"    //! Return the fields.",
"",
"@@BeginFieldLoop@@",
"    @!CARDINALITY!@@!Fieldtype!@	*get@!CARDINALITY!@@!Fieldname!@(void);",
"@@EndFieldLoop@@",
"",
"    /*----------------------------- access ----------------------------------*/",
"",
"    //!@{ Return the fields' values.",
"",
"@@BeginSFFieldLoop@@",
"          @!Fieldtype!@	&get@!Fieldname!@(void);",
"    const @!Fieldtype!@	&get@!Fieldname!@(void) const;",
"@@EndSFFieldLoop@@",
"",
"@@BeginMFFieldLoop@@",
"          @!Fieldtype!@	&get@!Fieldname!@( UInt32 index );",
"@@EndMFFieldLoop@@",
"",
"    //!@}",
"",
"    /*-------------------------- transformation ----------------------------*/",
"",
"    /*------------------------------ volume -------------------------------*/",
"",
"    /*------------------------------ dump -----------------------------------*/",
"",
"  protected:",
"",
"    //-----------------------------------------------------------------------",
"    //   enums                                                               ",
"    //-----------------------------------------------------------------------",
"",
"    //-----------------------------------------------------------------------",
"    //   types                                                               ",
"    //-----------------------------------------------------------------------",
"",
"    //-----------------------------------------------------------------------",
"    //   class variables                                                     ",
"    //-----------------------------------------------------------------------",
"",
"    //-----------------------------------------------------------------------",
"    //   class functions                                                     ",
"    //-----------------------------------------------------------------------",
"",
"    //-----------------------------------------------------------------------",
"    //   instance variables                                                  ",
"    //-----------------------------------------------------------------------",
"",
"    //! The fields storing the data.",
"",
"@@BeginFieldLoop@@",
"    @!CARDINALITY!@@!Fieldtype!@	_@!fieldname!@;",
"@@EndFieldLoop@@",
"",
"    //-----------------------------------------------------------------------",
"    //   instance functions                                                  ",
"    //-----------------------------------------------------------------------",
"",
"    @!Classname!@Base(void);",
"    @!Classname!@Base(const @!Classname!@Base &source);",
"    virtual ~@!Classname!@Base(void); ",
"    ",
"  private:",
"",
"    //-----------------------------------------------------------------------",
"    //   enums                                                               ",
"    //-----------------------------------------------------------------------",
"",
"    //-----------------------------------------------------------------------",
"    //   types                                                               ",
"    //-----------------------------------------------------------------------",
"",
"    //-----------------------------------------------------------------------",
"    //   friend classes                                                      ",
"    //-----------------------------------------------------------------------",
"",
"    friend class FieldContainer;",
"",
"    //-----------------------------------------------------------------------",
"    //   friend functions                                                    ",
"    //-----------------------------------------------------------------------",
"",
"    //-----------------------------------------------------------------------",
"    //   class variables                                                     ",
"    //-----------------------------------------------------------------------",
"",
"    static char cvsid[];",
"",
"    static FieldDescription   _desc[];",
"",
"    static FieldContainerType _type;",
"",
"    //-----------------------------------------------------------------------",
"    //   class functions                                                     ",
"    //-----------------------------------------------------------------------",
"",
"    //-----------------------------------------------------------------------",
"    //   instance variables                                                  ",
"    //-----------------------------------------------------------------------",
"",
"    //-----------------------------------------------------------------------",
"    //   instance functions                                                  ",
"    //-----------------------------------------------------------------------",
"",
"    // prohibit default functions (move to 'public' if you need one)",
"",
"    void operator =(const @!Classname!@ &source);",
"};",
"",
"//---------------------------------------------------------------------------",
"//   Exported Types",
"//---------------------------------------------------------------------------",
"",
"",
"/** \\brief class pointer",
" */",
"typedef @!Classname!@Base *@!Classname!@BaseP;",
"",
"@@PointerFieldDecl@@",
"",
"OSG_END_NAMESPACE",
"",
"#endif /* _OSG@!CLASSNAME!@BASE_H_ */",
NULL };
