char *FCBaseTemplate_cpp[]={
"/*---------------------------------------------------------------------------*\\",
" *                                OpenSG                                     *",
" *                                                                           *",
" *                                                                           *",
" *                 Copyright (C) 2000 by the OpenSG Forum                    *",
" *                                                                           *",
" *                            www.opensg.org                                 *",
" *                                                                           *",
" *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *",
" *                                                                           *",
"\\*---------------------------------------------------------------------------*/",
"/*---------------------------------------------------------------------------*\\",
" *                                License                                    *",
" *                                                                           *",
" * This library is free software; you can redistribute it and/or modify it   *",
" * under the terms of the GNU Library General Public License as published    *",
" * by the Free Software Foundation, version 2.                               *",
" *                                                                           *",
" * This library is distributed in the hope that it will be useful, but       *",
" * WITHOUT ANY WARRANTY; without even the implied warranty of                *",
" * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *",
" * Library General Public License for more details.                          *",
" *                                                                           *",
" * You should have received a copy of the GNU Library General Public         *",
" * License along with this library; if not, write to the Free Software       *",
" * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *",
" *                                                                           *",
"\\*---------------------------------------------------------------------------*/",
"/*---------------------------------------------------------------------------*\\",
" *                                Changes                                    *",
" *                                                                           *",
" *                                                                           *",
" *                                                                           *",
" *                                                                           *",
" *                                                                           *",
" *                                                                           *",
"\\*---------------------------------------------------------------------------*/",
"",
"//---------------------------------------------------------------------------",
"//  Includes",
"//---------------------------------------------------------------------------",
"",
"",
"#include <stdlib.h>",
"#include <stdio.h>",
"",
"#include \"OSGConfig.h\"",
"",
"#ifdef OSG_STREAM_IN_STD_NAMESPACE",
"#include <iostream>",
"#else",
"#include <iostream.h>",
"#endif",
"",
"#define OSG_COMPILE@!LIBNAME!@",
"#define OSG_COMPILE@!CLASSNAME!@INST",
"",
"#include \"OSG@!Classname!@Base.h\"",
"#include \"OSG@!Classname!@.h\"",
"",
"OSG_USING_NAMESPACE",
"",
"",
"/***************************************************************************\\",
" *                               Types                                     *",
"\\***************************************************************************/",
"",
"@@PointerFieldDef@@",
"",
"/***************************************************************************\\",
" *                           Class variables                               *",
"\\***************************************************************************/",
"",
"@@BeginFieldLoop@@",
"const OSG::UInt32		@!Classname!@Base::@!Fieldname!@FieldId;",
"const OSG::BitVector	@!Classname!@Base::@!Fieldname!@FieldMask;",
"",
"@@EndFieldLoop@@",
"",
"const OSG::UInt32    	@!Classname!@Base::NextFieldId; ",
"const OSG::BitVector 	@!Classname!@Base::NextFieldMask;",
"",
"",
"char @!Classname!@Base::cvsid[] = \"@(#)$Id: FCBaseTemplate_cpp.h,v 1.1 2001/03/29 04:16:44 dirk Exp $\";",
"",
"/** \\brief Group field description",
" */",
"",
"FieldDescription @!Classname!@Base::_desc[] = ",
"{",
"@@BeginFieldLoop@@",
"    FieldDescription(@!CARDINALITY!@@!Fieldtype!@::getClassType(), ",
"                     \"@!fieldname!@\", ",
"                     @!Fieldname!@FieldId, @!Fieldname!@FieldMask,",
"                     @!fieldvisibility!@,",
"                     (FieldAccessMethod) &@!Classname!@Base::get"
							"@!CARDINALITY!@@!Fieldname!@),",
"@@EndFieldLoop@@",
"};",
"",
"/** \\brief @!Classname!@ type",
" */",
"",
"FieldContainerType @!Classname!@Base::_type(",
"    \"@!Classname!@\",",
"    \"@!Parent!@\",",
"    NULL,",
"    (PrototypeCreateF) &@!Classname!@Base::createEmpty,",
"    @!Classname!@::initMethod,",
"    _desc,",
"    sizeof(_desc));",
"",
"",
"/***************************************************************************\\",
" *                           Class methods                                 *",
"\\***************************************************************************/",
"",
"/*-------------------------------------------------------------------------*\\",
" -  public                                                                 -",
"\\*-------------------------------------------------------------------------*/",
"",
"/***************************************************************************\\",
" *                           Class methods                                 *",
"\\***************************************************************************/",
"",
"/*-------------------------------------------------------------------------*\\",
" -  public                                                                 -",
"\\*-------------------------------------------------------------------------*/",
"",
"/*-------------------------------------------------------------------------*\\",
" -  protected                                                              -",
"\\*-------------------------------------------------------------------------*/",
"",
"/*-------------------------------------------------------------------------*\\",
" -  private                                                                -",
"\\*-------------------------------------------------------------------------*/",
"",
"/***************************************************************************\\",
" *                           Instance methods                              *",
"\\***************************************************************************/",
"",
"/*-------------------------------------------------------------------------*\\",
" -  public                                                                 -",
"\\*-------------------------------------------------------------------------*/",
"",
"//OSG_FIELD_CONTAINER_DEF(@!Classname!@Base, @!Classname!@Ptr)",
"",
"OSG::FieldContainerType &@!Classname!@Base::getType(void) ",
"{",
"    return _type; ",
"} ",
"",
"const OSG::FieldContainerType &@!Classname!@Base::getType(void) const ",
"{",
"    return _type;",
"} ",
"",
"OSG::FieldContainerPtr @!Classname!@Base::shallowCopy(void) const ",
"{ ",
"    @!Classname!@Ptr returnValue; ",
"",
"    newPtr(returnValue, dynamic_cast<const @!Classname!@ *>(this)); ",
"",
"    return returnValue; ",
"}",
"",
"OSG::UInt32 @!Classname!@Base::getSize(void) const ",
"{ ",
"    return sizeof(@!Classname!@Base); ",
"}",
"",
"/*------------- constructors & destructors --------------------------------*/",
"",
"/** \\brief Constructor",
" */",
"",
"@!Classname!@Base::@!Classname!@Base(void) :",
"@@BeginFieldLoop@@",
"	_@!fieldname!@	(@!FieldTypedDefault!@),",
"@@EndFieldLoop@@",
"	Inherited()",
"{",
"}",
"",
"/** \\brief Copy Constructor",
" */",
"",
"@!Classname!@Base::@!Classname!@Base(const @!Classname!@Base &source) :",
"@@BeginFieldLoop@@",
"	_@!fieldname!@		(source._@!fieldname!@),",
"@@EndFieldLoop@@",
"	Inherited        (source                  )",
"{",
"}",
"",
"/** \\brief Destructor",
" */",
"",
"@!Classname!@Base::~@!Classname!@Base(void)",
"{",
"}",
"",
"/*------------------------------ access -----------------------------------*/",
"",
"@@BeginFieldLoop@@",
"@!CARDINALITY!@@!Fieldtype!@ *@!Classname!@Base::get"
	"@!CARDINALITY!@@!Fieldname!@(void)",
"{",
"	return &_@!fieldname!@;",
"}",
"",
"@@EndFieldLoop@@",
"",
"@@BeginSFFieldLoop@@",
"@!Fieldtype!@ &@!Classname!@Base::get@!Fieldname!@(void)",
"{",
"	return _@!fieldname!@.getValue();",
"}",
"",
"const @!Fieldtype!@ &@!Classname!@Base::get@!Fieldname!@(void) const",
"{",
"	return _@!fieldname!@.getValue();",
"}",
"",
"@@EndSFFieldLoop@@",
"",
"@@BeginMFFieldLoop@@",
"@!Fieldtype!@ &@!Classname!@Base::get@!Fieldname!@( UInt32 index)",
"{",
"	return _@!fieldname!@.getValue( index );",
"}",
"",
"@@EndMFFieldLoop@@",
"",
"/*------------------------------- dump ----------------------------------*/",
"",
"/*-------------------------------------------------------------------------*\\",
" -  protected                                                              -",
"\\*-------------------------------------------------------------------------*/",
"",
"/*-------------------------------------------------------------------------*\\",
" -  private                                                                -",
"\\*-------------------------------------------------------------------------*/",
"",
NULL };
