/* This is a template file for fcdEdit.
 * To create it from sample source,  cut'n'paste the source and apply the following
 * substitutions:
 * s|\|\\|g 
 * s|"|\"|g 
 * s|^|"| 
 * s|$|",|
 */

char *FCTemplate_cpp[]={
"/*---------------------------------------------------------------------------*\\",
" *                                OpenSG                                     *",
" *                                                                           *",
" *                                                                           *",
" *             Copyright (C) 2000,2001 by the OpenSG Forum                   *",
" *                                                                           *",
" *                            www.opensg.org                                 *",
" *                                                                           *",
" *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *",
" *                                                                           *",
"\\*---------------------------------------------------------------------------*/",
"/*---------------------------------------------------------------------------*\\",
" *                                License                                    *",
" *                                                                           *",
" * This library is free software; you can redistribute it and/or modify it   *",
" * under the terms of the GNU Library General Public License as published    *",
" * by the Free Software Foundation, version 2.                               *",
" *                                                                           *",
" * This library is distributed in the hope that it will be useful, but       *",
" * WITHOUT ANY WARRANTY; without even the implied warranty of                *",
" * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *",
" * Library General Public License for more details.                          *",
" *                                                                           *",
" * You should have received a copy of the GNU Library General Public         *",
" * License along with this library; if not, write to the Free Software       *",
" * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *",
" *                                                                           *",
"\\*---------------------------------------------------------------------------*/",
"/*---------------------------------------------------------------------------*\\",
" *                                Changes                                    *",
" *                                                                           *",
" *                                                                           *",
" *                                                                           *",
" *                                                                           *",
" *                                                                           *",
" *                                                                           *",
"\\*---------------------------------------------------------------------------*/",
"",
"//---------------------------------------------------------------------------",
"//  Includes",
"//---------------------------------------------------------------------------",
"",
"#define OSG_COMPILE@!LIBNAME!@LIB",
"",
"#include <stdlib.h>",
"#include <stdio.h>",
"",
"#include <@!HeaderPrefix!@OSGConfig.h>",
"",
"#include \"OSG@!Classname!@.h\"",
"",
"OSG_USING_NAMESPACE",
"",
"#ifdef __sgi",
"#pragma set woff 1174",
"#endif",
"",
"namespace",
"{",
"    static char cvsid_cpp[] = \"@(#)$Id: FCTemplate_cpp.h,v 1.7 2001/09/17 14:15:07 vossg Exp $\";",
"    static char cvsid_hpp[] = OSG@!CLASSNAME!@_HEADER_CVSID;",
"    static char cvsid_inl[] = OSG@!CLASSNAME!@_INLINE_CVSID;",
"}",
"",
"#ifdef __sgi",
"#pragma reset woff 1174",
"#endif",
"",
"/*! \\class osg::@!Classname!@",
"@!Description!@",
"*/",
"",
"/*----------------------- constructors & destructors ----------------------*/",
"",
"//! Constructor",
"",
"@!Classname!@::@!Classname!@(void) :",
"    Inherited()",
"{",
"}",
"",
"//! Copy Constructor",
"",
"@!Classname!@::@!Classname!@(const @!Classname!@ &source) :",
"    Inherited(source)",
"{",
"}",
"",
"//! Destructor",
"",
"@!Classname!@::~@!Classname!@(void)",
"{",
"}",
"",
"/*------------------------------- class get -------------------------------*/",
"",
"static const char *getClassname(void)",
"{",
"    return \"@!Classname!@\"; ",
"};",
"",
"/*----------------------------- class specific ----------------------------*/",
"",
"//! initialize the static features of the class, e.g. action callbacks",
"",
"void @!Classname!@::initMethod (void)",
"{",
"}",
"",
"//! react to field changes",
"",
"void @!Classname!@::changed(BitVector, ChangeMode)",
"{",
"}",
"",
"//! output the instance for debug purposes",
"",
"void @!Classname!@::dump(      UInt32     uiIndent, ",
"                         const BitVector &bvFlags) const",
"{",
"	SLOG << \"Dump @!Classname!@ NI\" << endl;", 
"}",
"",
NULL};
