Import('*')

sources = Split("""
    FieldContainer.cpp
    FieldContainerViewCtl.cpp
    Field.cpp
    main.cpp
    ParseComandLine.cpp
    FieldContainerView.ui
""")

def custom(env):
    env['CXXFILESUFFIX'] = '.cpp'
    env['QT_HPREFIX'] = 'uic_'
    env.Append(CPPPATH = ['$OSG_OBJDIR'])

if tc.is_win32():
    dep_LIBS = ['OSGWindowWIN32']
else:
    dep_LIBS = ['OSGWindowX']


#BuildProgram(tc, 'fcdEdit', sources, tools=['qt'],
#             updates=[custom, OpenSGLibrary(['OSGWindowQT', 'OSGSystem', 'OSGBase'] + dep_LIBS)],
#             CPPPATH=[Dir('.'), Dir('$OSG_OBJDIR'), env['PREFIX'].Dir('include')],
#             CPPDEFINES=['OSG_WITH_QT', 'OSG_BUILD_DLL'])
